apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - mainapi-deployment.yaml
  - transaction-consumer-deployment.yaml

images:
  - name: ghcr.io/jaturapornchai/bccode-mainapi
    newTag: replace-me
