// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Windows ใช้ test06 project สำหรับ Google Sign-In
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChVSQ_yXhu6NRQ9LbKWkOJ_OB_fxUEsmw',
    appId: '1:381991785720:web:100679811f28ea7e87570d',
    messagingSenderId: '381991785720',
    projectId: 'test06-a1240',
    storageBucket: 'test06-a1240.firebasestorage.app',
    authDomain: 'test06-a1240.firebaseapp.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV8wwIwLSsMEefD-cD0FAgBRgIr4SLISk',
    appId: '1:183871505957:web:97c3142269fffda907a1cc',
    messagingSenderId: '183871505957',
    projectId: 'dedepos',
    authDomain: 'dedepos.firebaseapp.com',
    storageBucket: 'dedepos.appspot.com',
    measurementId: 'G-KDQND6XX0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHfJ-wnQfzD4BSQeXggora43ygd5sRwcU',
    appId: '1:183871505957:android:259560e2a480d0ed07a1cc',
    messagingSenderId: '183871505957',
    projectId: 'dedepos',
    storageBucket: 'dedepos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ931rkxwdcUScQBvgGK8aAhBYsM6-kbY',
    appId: '1:183871505957:ios:e9ab0b0f040d909107a1cc',
    messagingSenderId: '183871505957',
    projectId: 'dedepos',
    storageBucket: 'dedepos.appspot.com',
    androidClientId:
        '183871505957-f4afcfn804071c18ujqjlgb1gth2d7kv.apps.googleusercontent.com',
    iosClientId:
        '183871505957-n8ieio3fg5tmj0vs3dhkvqcg4sm5tti9.apps.googleusercontent.com',
    iosBundleId: 'com.dede.merchant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ931rkxwdcUScQBvgGK8aAhBYsM6-kbY',
    appId: '1:183871505957:ios:1ae71de258f209fd07a1cc',
    messagingSenderId: '183871505957',
    projectId: 'dedepos',
    storageBucket: 'dedepos.appspot.com',
    androidClientId:
        '183871505957-f4afcfn804071c18ujqjlgb1gth2d7kv.apps.googleusercontent.com',
    iosClientId:
        '183871505957-c2nsuupode4pc5uefg4n731onppjo6q8.apps.googleusercontent.com',
    iosBundleId: 'smlaicloud.smlaicloud',
  );
}
