apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/jaturapornchai/bccode-mainapi
    newName: bc-ai-account/mainapi
    newTag: local

patches:
  - path: mainapi-local-patch.yaml
  - path: transaction-consumer-local-patch.yaml
  - path: ingress-local-patch.yaml
  - path: remove-hpa-pdb-local.yaml
