apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mainapi
  namespace: bc-ai-account
$patch: delete
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: transaction-consumer
  namespace: bc-ai-account
$patch: delete
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mainapi
  namespace: bc-ai-account
$patch: delete
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: transaction-consumer
  namespace: bc-ai-account
$patch: delete
