import {
  Activity,
  Archive,
  ArchiveRestore,
  BarChart3,
  Badge,
  Bell,
  BriefcaseBusiness,
  Building2,
  Bot,
  Boxes,
  Calculator,
  CalendarCheck,
  ChartNoAxesColumn,
  CheckCheck,
  ChefHat,
  CircleDollarSign,
  CloudDownload,
  CloudSync,
  CreditCard,
  DraftingCompass,
  Globe,
  Download,
  FileCog,
  FileText,
  Folder,
  FolderGit2,
  Gift,
  GitBranch,
  Grid2X2,
  HandCoins,
  Home,
  Image,
  ImagePlus,
  Images,
  Inbox,
  KeyRound,
  Landmark,
  Link2,
  List,
  MapPin,
  MapPinned,
  MonitorCog,
  Network,
  Package,
  Palette,
  Printer,
  QrCode,
  ReceiptText,
  Ruler,
  Settings,
  ShieldCheck,
  ShoppingBasket,
  ShoppingCart,
  Store,
  Table2,
  Tag,
  Truck,
  Undo2,
  Upload,
  UserPlus,
  UserRound,
  UsersRound,
  Warehouse,
  type LucideIcon,
} from "lucide-react";
import type { MenuItem } from "@/lib/menu-data";
import { menuIconKeyForRoute, type MenuIconKey } from "@/lib/menu-icons";

const MENU_ICON_COMPONENTS: Record<MenuIconKey, LucideIcon> = {
  activity: Activity,
  archive: Archive,
  badge: Badge,
  bank: Landmark,
  barChart: BarChart3,
  bot: Bot,
  boxes: Boxes,
  branch: GitBranch,
  briefcase: BriefcaseBusiness,
  building: Building2,
  calendarCheck: CalendarCheck,
  calculator: Calculator,
  category: Tag,
  check: CheckCheck,
  cloudDownload: CloudDownload,
  cloudSync: CloudSync,
  color: Palette,
  creditCard: CreditCard,
  currency: CircleDollarSign,
  department: Network,
  design: DraftingCompass,
  download: Download,
  fileChart: ChartNoAxesColumn,
  fileCog: FileCog,
  fileText: FileText,
  folder: Folder,
  gift: Gift,
  globe: Globe,
  grid: Grid2X2,
  group: FolderGit2,
  import: Upload,
  inbox: Inbox,
  inventory: Package,
  key: KeyRound,
  kitchen: ChefHat,
  link: Link2,
  list: List,
  location: MapPin,
  map: MapPinned,
  media: Image,
  money: CircleDollarSign,
  network: Network,
  notification: Bell,
  outbox: ArchiveRestore,
  package: Package,
  payment: HandCoins,
  photoAdd: ImagePlus,
  photoLibrary: Images,
  pos: MonitorCog,
  print: Printer,
  project: FolderGit2,
  qr: QrCode,
  receipt: ReceiptText,
  return: Undo2,
  ruler: Ruler,
  sale: ShoppingCart,
  settings: Settings,
  shield: ShieldCheck,
  shoppingBasket: ShoppingBasket,
  shoppingCart: ShoppingCart,
  store: Store,
  table: Table2,
  tag: Tag,
  truck: Truck,
  upload: Upload,
  user: UserRound,
  userAdd: UserPlus,
  users: UsersRound,
  warehouse: Warehouse,
  work: BriefcaseBusiness,
};

export function MenuRouteIcon({ item, size = 18 }: { item: MenuItem; size?: number }) {
  const Icon = MENU_ICON_COMPONENTS[menuIconKeyForRoute(item.route, item.category)] ?? Grid2X2;
  return <Icon aria-hidden="true" size={size} />;
}

export function HomeMenuIcon({ size = 18 }: { size?: number }) {
  return <Home aria-hidden="true" size={size} />;
}
