/**
 * UI string pack for Product Barcode screens.
 *
 * Source of truth note:
 * backend `assets/language/languages.tsv` is the canonical label registry.
 * The keys below should eventually be backed by language API; until those keys
 * land in TSV we keep a local Thai/English fallback so the screen ships.
 * Each key here SHOULD have a matching entry in TSV — see
 * `backend/prompts/language_requests/product-barcode-screen.md` for batch.
 */

import { type LanguageCode, normalizeLanguage } from "@/lib/i18n";

export type BarcodeText = typeof barcodeTextTh;

const barcodeTextTh = {
  // Page
  title: "บาร์โค้ด",
  subtitle: "จัดการบาร์โค้ด SKU หน่วยขาย ราคา และข้อมูลอ้างอิงสินค้า",
  tenant: "บริษัท",
  branch: "สาขา",

  // Toolbar
  refresh: "รีเฟรช",
  export: "ส่งออก",
  import: "นำเข้า",
  selectDelete: "เลือกเพื่อลบ",
  cancelSelect: "ยกเลิกเลือก",
  add: "เพิ่ม",
  search: "ค้นหา บาร์โค้ด ชื่อสินค้า หรือรหัสสินค้า",
  filter: "ตัวกรอง",
  sortBy: "เรียงตาม",
  sortOrder: "ลำดับ",
  sortAsc: "น้อย → มาก",
  sortDesc: "มาก → น้อย",
  showImage: "แสดงรูป",
  hideImage: "ซ่อนรูป",

  // Filter fields
  groupCode: "กลุ่มสินค้า",
  brandCode: "ยี่ห้อ",
  categoryCode: "หมวดสินค้า",
  classCode: "Class",
  designCode: "Design",
  gradeCode: "Grade",
  modelCode: "Model",
  patternCode: "Pattern",
  priceMin: "ราคาต่ำสุด",
  priceMax: "ราคาสูงสุด",
  clearFilter: "ล้างตัวกรอง",
  applyFilter: "ใช้ตัวกรอง",

  // List columns
  total: "ทั้งหมด",
  selected: "เลือกแล้ว",
  barcode: "บาร์โค้ด",
  productName: "ชื่อสินค้า",
  unit: "หน่วย",
  itemCode: "รหัสสินค้า",
  balance: "คงเหลือ",
  retailPrice: "ราคาขาย",
  image: "รูป",
  actions: "การจัดการ",

  // Detail / Form
  detailTitle: "รายละเอียดบาร์โค้ด",
  noSelection: "เลือกรายการด้านซ้ายเพื่อดูรายละเอียด",
  loading: "กำลังโหลดข้อมูลบาร์โค้ด",
  noData: "ไม่พบข้อมูลบาร์โค้ด",
  apiRequired: "กรุณาเข้าสู่ระบบและเลือกบริษัทก่อนเปิดหน้าจอนี้",
  requestFailed: "โหลดข้อมูลไม่สำเร็จ",
  edit: "แก้ไข",
  save: "บันทึก",
  saving: "กำลังบันทึก…",
  close: "ปิด",
  cancel: "ยกเลิก",
  createTitle: "เพิ่มบาร์โค้ด",
  editTitle: "แก้ไขบาร์โค้ด",
  copy: "คัดลอก",
  delete: "ลบ",
  preview: "ตัวอย่าง",
  saveSuccess: "บันทึกบาร์โค้ดแล้ว",
  deleteConfirm: "ต้องการลบบาร์โค้ดที่เลือกจริงหรือไม่",
  deleteSuccess: "ลบบาร์โค้ดแล้ว",
  missingGuid: "รายการที่เลือกไม่มี GUID สำหรับลบ",
  exportSuccess: "ส่งออกข้อมูลที่แสดงอยู่แล้ว",
  productMasterTitle: "ข้อมูลสินค้าหลัก",
  productMasterSubtitle: "จัดการสินค้าหลักและผูกความสัมพันธ์กับบาร์โค้ด",
  productMasterSearch: "ค้นหาชื่อ หรือรหัสสินค้า",
  productMasterAdd: "เพิ่มสินค้า",
  productMasterDetailTitle: "รายละเอียดสินค้าหลัก",
  productMasterCreateTitle: "เพิ่มสินค้าใหม่",
  productMasterEditTitle: "แก้ไขสินค้า",
  productMasterSaveSuccess: "บันทึกสินค้าแล้ว",
  productMasterDeleteConfirm: "ต้องการลบสินค้านี้จริงหรือไม่?",
  productMasterDeleteSuccess: "ลบสินค้าสำเร็จ",
  productMasterCodeRequired: "กรุณากรอกรหัสสินค้า",
  productMasterNameRequired: "กรุณากรอกชื่อสินค้าอย่างน้อย 1 ภาษา",
  codeRequired: "กรุณากรอกรหัสสินค้า",
  nameRequired: "กรุณากรอกชื่อสินค้าอย่างน้อย 1 ภาษา",
  manufacturers: "ผู้ผลิต (ได้หลายคน)",
  addManufacturer: "เพิ่มผู้ผลิต",
  suppliers: "ผู้จำหน่าย/ผู้ขาย (ได้หลายคน)",
  addSupplier: "เพิ่มผู้จำหน่าย",
  groupsubone: "กลุ่มย่อย 1",
  groupsubtwo: "กลุ่มย่อย 2",
  class: "คลาสสินค้า",

  // Quick actions
  bomView: "ดูสูตรการผลิต",
  priceHistory: "ประวัติราคา",
  labelPrint: "พิมพ์ป้ายสินค้า",

  // Tabs
  tabBasic: "ข้อมูลหลัก",
  tabClassification: "หมวดหมู่",
  tabPricing: "ราคา",
  tabStock: "คงคลัง",
  tabUnits: "หน่วยและการแปลง",
  tabBom: "สูตรการผลิต (BOM)",
  tabMedia: "ภาพและสี",
  tabRestaurant: "ร้านอาหาร/POS",
  tabTimeForSales: "เวลาขาย",
  tabDimensions: "ขนาด",
  tabBusinessBranch: "ธุรกิจ/สาขา",
  tabMisc: "อื่นๆ",
  tabProductDetail: "ข้อมูลสินค้าหลัก",

  // Basic tab
  required: "จำเป็น",
  optional: "ไม่บังคับ",
  barcodeHelp: "เฉพาะ A-Z, 0-9, - (ไม่เว้นวรรค)",
  names: "ชื่อสินค้า",
  product: "สินค้าหลัก",
  addLanguage: "เพิ่มภาษาอื่น",
  otherLanguage: "ภาษาอื่น",
  multiUnit: "หลายหน่วย",
  itemUnit: "หน่วยนับ",
  itemUnitSize: "ขนาดต่อหน่วย",
  itemType: "ประเภทไอเทม",
  itemTypeStock: "สินค้ามีสต๊อก",
  itemTypeService: "สินค้าบริการ",
  itemTypeSet: "สินค้าชุด",
  itemTypeNotStock: "สินค้าไม่คุมสต๊อก",
  materialType: "ประเภทสินค้า",
  materialGeneral: "สินค้าทั่วไป",
  materialMaterial: "วัตถุดิบ",
  materialSemiFinished: "กึ่งสำเร็จรูป",
  materialSet: "สินค้าชุด",
  materialAgricultural: "สินค้าเกษตร",
  vatType: "ประเภทภาษี",
  vatIncluded: "สินค้ามีภาษีมูลค่าเพิ่ม",
  vatExcluded: "สินค้ายกเว้นภาษีมูลค่าเพิ่ม",
  taxType: "ประเภทภาษี",
  vatCal: "วิธีคำนวณ VAT",
  isMainBarcode: "บาร์โค้ดหลัก",
  isStock: "ตัดสต๊อก",

  // Classification tab
  group: "กลุ่มสินค้า",
  groupSubOne: "หมวดย่อย 1",
  groupSubTwo: "หมวดย่อย 2",
  brand: "ยี่ห้อ",
  category: "หมวดสินค้า",
  classification: "Class",
  design: "Design",
  grade: "เกรด",
  model: "Model",
  pattern: "Pattern",
  manufacturer: "ผู้ผลิต",
  productType: "ประเภทสินค้า (POS)",

  // Pricing tab
  prices: "ราคาขาย",
  priceKey: "ระดับราคา",
  price: "ราคา",
  addPrice: "เพิ่มระดับราคา",
  fixedCost: "ต้นทุนมาตรฐาน",
  fixedCostDate: "วันที่มีผล",
  fixedCostAmount: "ต้นทุน",
  addFixedCost: "เพิ่มต้นทุน",
  discount: "ส่วนลด",
  maxDiscount: "ส่วนลดสูงสุด",
  isDividend: "ใช้สิทธิ์ปันผล",
  isDiscountPointOfPurchase: "ส่วนลด ณ จุดขาย",

  // Stock tab
  orderPoint: "Order Point",
  minPoint: "Min",
  maxPoint: "Max",
  qty: "จำนวนคงเหลือ",
  stockBarcode: "Barcode อ้างอิงสต๊อก",

  // Units tab
  divideValue: "ตัวหาร (Divide)",
  standValue: "ค่ามาตรฐาน (Stand)",
  condition: "Condition",
  isUseSubBarcodes: "ใช้บาร์โค้ดอ้างอิง",
  refBarcodes: "บาร์โค้ดอ้างอิง",
  refBarcodeAdd: "เพิ่มบาร์โค้ดอ้างอิง",
  refBarcodeQty: "จำนวนต่อหน่วย",
  refUnitNames: "หน่วยอ้างอิง",

  // BOM tab
  bom: "สูตรการผลิต (BOM)",
  bomAdd: "เพิ่มรายการ",
  bomQty: "จำนวน",
  bomBarcode: "บาร์โค้ดวัตถุดิบ",
  bomPreview: "ดูแผนภาพ",

  // Media tab
  useImageOrColor: "ใช้รูปภาพหรือสี",
  imageMain: "รูปหลัก",
  imageUpload: "อัปโหลดรูป",
  imageDelete: "ลบรูป",
  imageGallery: "รูปเพิ่มเติม",
  colorPick: "เลือกสี",
  colorName: "ชื่อสี",
  colorHex: "รหัสสี (HEX)",

  // Restaurant tab
  isForRestaurant: "ทานที่ร้าน",
  isForTakeaway: "สั่งกลับบ้าน",
  isForDelivery: "เดลิเวอรี่",
  isForCustomer: "ลูกค้าสั่งได้",
  isForCustomerPreOrder: "Pre-order",
  isALaCarte: "à la carte",
  isStockForRestaurant: "ตัดสต๊อกสำหรับร้านอาหาร",
  isSplitUnitPrint: "แยกพิมพ์ตามหน่วย",
  isOnlyStaff: "เฉพาะพนักงาน",
  foodType: "ประเภทอาหาร",
  foodTypeFood: "อาหาร",
  foodTypeDrink: "เครื่องดื่ม",
  foodTypeAlcohol: "แอลกอฮอล์",
  foodTypeOther: "อื่นๆ",
  orderTypes: "ประเภทการสั่ง",
  orderTypeChargePrice: "ราคาเพิ่ม",
  orderTypeAdd: "เพิ่มประเภทการสั่ง",
  options: "ตัวเลือกเสริม",
  optionAdd: "เพิ่มตัวเลือก",
  optionType: "ชนิดตัวเลือก",
  optionTypeMulti: "เลือกได้หลายอย่าง",
  optionTypeSingle: "เลือกได้หนึ่งอย่าง",
  optionMinSelect: "เลือกอย่างน้อย",
  optionMaxSelect: "เลือกได้สูงสุด",
  optionChoices: "ตัวเลือก",
  optionChoiceAdd: "เพิ่มตัวเลือก",
  optionChoicePrice: "ราคาเพิ่ม",
  optionChoiceIsStock: "ตัดสต๊อก",
  optionChoiceIsDefault: "เลือกโดยปริยาย",
  optionChoiceRefBarcode: "บาร์โค้ดอ้างอิง",
  optionChoiceQty: "จำนวนต่อหน่วย",

  // TimeForSales tab
  timeForSales: "ช่วงเวลาที่ขายได้",
  timeForSalesAdd: "เพิ่มช่วงเวลา",
  fromDate: "ตั้งแต่วันที่",
  toDate: "ถึงวันที่",
  fromTime: "ตั้งแต่เวลา",
  toTime: "ถึงเวลา",
  daysOfWeek: "วันในสัปดาห์",
  sun: "อา",
  mon: "จ",
  tue: "อ",
  wed: "พ",
  thu: "พฤ",
  fri: "ศ",
  sat: "ส",

  // Dimensions tab
  dimensions: "ขนาด",
  dimensionAdd: "เพิ่มขนาด",
  dimensionGroup: "หมวดขนาด",
  dimensionItem: "ค่า",

  // Business / Branch tab
  businessTypes: "ประเภทธุรกิจ",
  businessTypeAdd: "เพิ่มประเภทธุรกิจ",
  ignoreBranches: "สาขาที่ไม่ขาย",
  ignoreBranchAdd: "เพิ่มสาขา",
  branchHint: "สาขาที่ติ๊กจะไม่สามารถขายสินค้านี้ได้",

  // Misc tab
  isSumPoint: "คะแนนสะสม",
  isSumPointYes: "คิดคะแนนสะสม",
  isSumPointNo: "ไม่คิดคะแนนสะสม",
  isAlert: "แจ้งเตือน",
  alertDescription: "ข้อความแจ้งเตือน",
  description: "หมายเหตุ / รายละเอียด",
  xsorts: "ลำดับการแสดงผล",
  holdingCode: "บริษัท",
  guid: "GUID",
  refGuid: "GUID อ้างอิง",
  itemGuid: "GUID สินค้า",

  // Picker
  pickerSearch: "ค้นหา",
  pickerClose: "ปิด",
  pickerSelect: "เลือก",
  pickerNoResult: "ไม่พบข้อมูล",
  pickerLoading: "กำลังโหลด…",
  pickerClear: "ล้างค่า",

  // Common
  yes: "ใช่",
  no: "ไม่",
  on: "เปิด",
  off: "ปิด",
  required_error: "จำเป็นต้องระบุ",
  invalidBarcode: "บาร์โค้ดต้องเป็น A-Z, 0-9 หรือ - เท่านั้น",
  unsavedChanges: "มีการแก้ไขที่ยังไม่บันทึก ต้องการออกหรือไม่?",

  // Detail-view section labels (barcode-screen detail panel)
  basicInfo: "ข้อมูลหลัก",
  classificationSection: "กลุ่ม/หมวด/คุณสมบัติ",
  stockAndUnit: "หน่วยนับ/สต็อก/ราคา",
  taxAndFlags: "ภาษีและสถานะ",
  relations: "ข้อมูลเชื่อมโยง",
  rawFields: "ข้อมูลทั้งหมดจาก API",

  // Extra barcode-screen field labels
  barcodeRef: "บาร์โค้ดอ้างอิง",
  shelf: "ชั้นวาง",
  color: "สี",
  unitCount: "จำนวนหน่วยนับ",
  isMainItem: "สินค้าหลัก",
  subGroup1: "กลุ่มย่อย 1",
  subGroup2: "กลุ่มย่อย 2",
  subBarcodes: "บาร์โค้ดย่อย",
  branches: "สาขา",
  categories: "หมวดสินค้า",
  isDisable: "ปิดใช้งาน",
  showIsDividend: "ข้อความปันผล",
  rowNumber: "ลำดับแถว",
  itemGuidFixed: "GUID สินค้าถาวร",
  parentGuid: "GUID แม่",
  checksum: "Checksum",

  // Barcode screen dialog / confirm strings
  jsonPayload: "ข้อมูล JSON ครบทุก field",
  invalidJson: "JSON ไม่ถูกต้อง",
  deleteCurrentConfirm: "ต้องการลบบาร์โค้ดจริงหรือไม่",
  unsavedConfirm: "มีข้อมูลที่ยังไม่ได้บันทึก ต้องการทิ้งการแก้ไขหรือไม่?",

  // product-screen tab labels
  tabUnitsBarcode: "หน่วยนับและบาร์โค้ด",
  tabBomShort: "ส่วนประกอบ (BOM)",
  tabBusinessBranchShort: "สาขา/ธุรกิจ",

  // product-screen inline section headers
  productTypeSection: "ประเภทสินค้าหลัก",
  itemTypeLabel: "ประเภทไอเทม",
  materialTypeLabel: "ประเภทสินค้า",
  groupsAndCategories: "ประเภทกลุ่ม & หมวดหมู่หลัก",
  groupsAndCategoriesEn: "Groups & Categories",
  basicInfoCard: "ข้อมูลเบื้องต้น",
  groupingCard: "การจัดกลุ่ม",
  noManufacturerData: "ยังไม่มีรายชื่อผู้ผลิต",
  noSupplierData: "ยังไม่มีรายชื่อผู้จำหน่าย",
  noManufacturerInfo: "ไม่มีข้อมูลผู้ผลิต",
  noSupplierInfo: "ไม่มีข้อมูลผู้จำหน่าย",
  backToList: "กลับสู่รายการสินค้า",
  backToListEn: "Back to list",
  pullFromBarcode: "ดึงข้อมูลจากบาร์โค้ดขายด่วน",
  selectUnlinkedBarcode: "เลือกบาร์โค้ดขายด่วนที่ยังไม่ผูกสินค้าหลัก",
  searchBarcodeOrName: "ค้นหาด้วยบาร์โค้ด หรือชื่อสินค้า...",
  searchingBarcode: "กำลังค้นหาบาร์โค้ด...",
  noUnlinkedBarcode: "ไม่พบข้อมูลบาร์โค้ดที่ยังไม่ผูกสินค้าหลัก",
  allBarcodesLinked: "ไม่มีบาร์โค้ดจรค้างอยู่ในระบบ (ทุกบาร์โค้ดผูกสินค้าหลักหมดแล้ว)",
  closeWindow: "ปิดหน้าต่าง",
  noName: "ไม่มีชื่อ",
  unitLabel: "หน่วยนับ",
  barcodeFetchSuccess: "ดึงข้อมูลจากบาร์โค้ด %s สำเร็จ กรุณาตรวจสอบรหัสสินค้าหลักและบันทึกข้อมูล",
  barcodeFetchFail: "ไม่สามารถดึงข้อมูลรายละเอียดบาร์โค้ดได้",

  // barcode-form TabProductDetail section titles
  classificationSectionTitle: "กลุ่มสินค้า & หมวดหมู่ (Classifications)",
  creditorsSectionTitle: "ผู้ผลิต & ผู้จัดจำหน่าย (Creditors)",
  mediaSectionTitle: "ภาพและสีป้ายสินค้า (Media)",
  restaurantSectionTitle: "การตั้งค่าสำหรับร้านอาหาร / POS",
  timeSectionTitle: "ช่วงเวลาที่ขายได้ & อื่นๆ",
  manufacturersLabel: "ผู้ผลิต (Manufacturers)",
  suppliersLabel: "ผู้จัดจำหน่าย (Suppliers)",
  galleryLabel: "แกลเลอรี่รูปภาพเพิ่มเติม",
  noImage: "ไม่มีรูป",
  displayMode: "รูปแบบแสดงผล",
  displayModeImage: "แสดงรูปภาพสินค้า",
  displayModeColor: "แสดงสีป้ายสินค้า",
  tagColor: "สีป้ายสินค้า",
  isForRestaurantLabel: "ทานที่ร้าน",
  isForTakeawayLabel: "สั่งกลับบ้าน",
  isForDeliveryLabel: "เดลิเวอรี่",
  isForCustomerLabel: "ลูกค้าสั่งเองได้",
  isForCustomerPreOrderLabel: "Pre-order ลูกค้า",
  isStockForRestaurantLabel: "ตัดสต๊อกร้านอาหาร",
  isSplitUnitPrintLabel: "แยกพิมพ์ตามหน่วย",
  isOnlyStaffLabel: "เฉพาะพนักงานขาย (Staff Only)",
  foodTypeSectionLabel: "ประเภทอาหาร (Food Type)",
  optionsSectionLabel: "ตัวเลือกเสริม (Options)",
  optionTypeMultiLabel: "เลือกได้หลายอย่าง",
  optionTypeSingleLabel: "เลือกได้อย่างเดียว",
  optionSelectRange: "เลือกได้ %min-%max อย่าง",
  alertToggleLabel: "เปิดใช้ข้อความแจ้งเตือนขณะขาย",
  alertMessageLabel: "ข้อความแจ้งเตือน",
  descriptionLabel: "รายละเอียดเพิ่มเติม",
  inheritedInfoBanner: "ข้อมูลสืบทอดจากสินค้าหลัก:",
  inheritedInfoDetail: "ข้อมูลการจัดกลุ่ม คู่ค้า รูปภาพ และการตั้งค่า POS ของบาร์โค้ดนี้ถูกสืบทอดมาจากสินค้าหลัก",
  inheritedInfoEditHint: "หากต้องการแก้ไขข้อมูลเหล่านี้ กรุณาไปที่เมนู",
  productMenuName: "สินค้า",
  loadingProductDetail: "กำลังดึงข้อมูลรายละเอียดสินค้าหลัก...",
  noProductDetailFound: "ไม่พบข้อมูลสินค้าหลักในระบบ กรุณาตรวจสอบการผูกสินค้าหลักที่แท็บข้อมูลหลัก",

  // product-screen sub-component labels (media, units, BOM, options, time, business, misc)
  mediaUseSection: "การใช้รูปภาพหรือสีป้ายสินค้า",
  mediaMainSection: "รูปภาพหลักของสินค้า",
  mediaGallerySection: "แกลเลอรี่รูปภาพเพิ่มเติม",
  mediaAddGallery: "เพิ่มรูปแกลเลอรี่",
  mediaColorSection: "ระบุสีป้ายสินค้า",
  mediaUploading: "กำลังอัปโหลด...",
  mediaUploadBtn: "อัปโหลดรูปภาพ",
  mediaDeleteBtn: "ลบรูปภาพ",
  mediaNoGallery: "— ไม่มีรูปภาพในแกลเลอรี่ —",
  mediaColorName: "ชื่อสี",
  mediaColorHex: "เลือกสีป้ายสินค้า (Hex)",
  mediaNoImage: "ไม่มีรูปภาพ",
  optionGroupName: "ชื่อกลุ่มตัวเลือกเสริม",
  optionChoiceType: "ประเภทการเลือก",
  optionChoiceTypeMulti: "เลือกได้หลายรายการ (Checkbox)",
  optionChoiceTypeSingle: "เลือกได้รายการเดียว (Radio)",
  optionMinSelectLabel: "จำนวนเลือกขั้นต่ำ (Min Select)",
  optionMaxSelectLabel: "จำนวนเลือกสูงสุด (Max Select)",
  optionChoiceName: "ชื่อตัวเลือกย่อย",
  optionChoicePriceLabel: "ราคาเพิ่มเติม",
  optionChoiceQtyLabel: "จำนวน",
  optionChoiceDefaultLabel: "ตัวเลือกเริ่มต้น (Default)",
  optionChoiceStockLabel: "หักสต็อกสินค้าเสริม",
  optionAddGroup: "เพิ่มกลุ่มตัวเลือกเสริม",
  optionAddChoice: "เพิ่มตัวเลือกย่อย",
  optionGroupNo: "กลุ่มตัวเลือกที่ #",
  optionChoiceNo: "ตัวเลือกย่อย #",
  optionChoiceList: "รายการตัวเลือกย่อย",
  timeSection: "ช่วงเวลาขายสินค้า (Time For Sale Settings)",
  timeAddBtn: "เพิ่มกำหนดเวลาขาย",
  timeNoLimit: "— สินค้าตัวนี้สามารถสแกนขายได้ตลอดเวลา —",
  timeDaysLabel: "วันในสัปดาห์",
  timeRuleNo: "ข้อกำหนดเวลาขายที่ #",
  timeFromDate: "ตั้งแต่วันที่",
  timeToDate: "ถึงวันที่",
  timeFromTime: "ตั้งแต่เวลา",
  timeToTime: "ถึงเวลา",
  businessTypeSection: "ยกเว้นการขายตามประเภทธุรกิจ",
  businessTypeAddBtn: "เพิ่มประเภทธุรกิจที่ยกเว้น",
  businessTypeNoData: "— ไม่มีการยกเว้น ขายได้ทุกประเภทธุรกิจ —",
  branchSection: "สาขาที่ยกเว้นการขายสินค้าตัวนี้",
  branchAddBtn: "เพิ่มสาขาที่ห้ามขาย",
  branchHintDetail: "สาขาที่เพิ่มเข้าในรายการนี้ จะไม่สามารถสแกนขายหรือเช็คสต็อกสินค้าชิ้นนี้ได้",
  branchNoData: "— ไม่มีสาขาที่ยกเว้น ขายได้ทุกสาขา —",
  pickerBranch: "สาขา",
  pickerBusinessType: "ประเภทธุรกิจ",
  miscAlertSection: "ข้อความแจ้งเตือนป๊อปอัปหน้าร้าน",
  miscAlertToggle: "เปิดใช้งานข้อความแจ้งเตือนขณะสแกนขาย",
  miscAlertDetail: "รายละเอียดข้อความแจ้งเตือน",
  miscDescSection: "คำอธิบาย/รายละเอียดสินค้าเพิ่มเติม",
  miscGuidSection: "ID / GUID ข้อมูลอ้างอิง",
  miscGuidFixed: "สินค้า GUID Fixed",
  miscHoldingCode: "รหัสร้านค้า (Holding Code)",
  miscUnitGuid: "รหัสหน่วยนับพื้นฐาน GUID",
  unitSection: "หน่วยนับและอัตราส่วน (Unit conversion)",
  unitBaseUnit: "หน่วยนับหลัก (Base Unit)",
  unitBasePlaceholder: "คลิกเลือกหน่วยนับหลัก...",
  unitDivide: "ตัวหาร (Divide Value)",
  unitStand: "ตัวคูณ (Stand Value)",
  unitCondition: "มีเงื่อนไขหน่วยนับ (Has Condition)",
  unitConditionEnable: "เปิดใช้งาน",
  unitMultiSection: "การจัดการบาร์โค้ดหลายหน่วยนับ (Multi-unit Barcodes)",
  unitMultiToggle: "เปิดใช้งานบาร์โค้ดหลายหน่วยนับ (Use Multi-unit Barcodes)",
  unitRefListTitle: "รายการบาร์โค้ดหน่วยนับเสริม",
  unitRefAddBtn: "เพิ่มบาร์โค้ดหน่วยนับเสริม",
  unitRefNoData: "ไม่มีรายการบาร์โค้ดหน่วยนับเสริม",
  unitRefBarcode: "บาร์โค้ด",
  unitRefBarcodePlaceholder: "ระบุบาร์โค้ดหน่วยย่อย",
  unitRefUnitCode: "หน่วยนับ (Unit Code)",
  unitRefUnitPlaceholder: "เช่น PCS, BOX",
  unitRefQty: "จำนวนขายย่อย (Qty)",
  unitRefDivide: "ตัวหาร",
  unitRefStand: "ตัวคูณ",
  bomSection: "สูตรการผลิตสินค้า (BOM - Bill of Materials)",
  bomAddBtn: "เพิ่มรายการวัตถุดิบ",
  bomNoData: "ไม่มีรายการวัตถุดิบในสูตร BOM",
  bomBarcodeLabel: "บาร์โค้ดวัตถุดิบ",
  bomBarcodePlaceholder: "สแกนหรือพิมพ์บาร์โค้ดวัตถุดิบ",
  bomUnitLabel: "หน่วยนับวัตถุดิบ",
  bomUnitPlaceholder: "เช่น PCS, KG",
  bomQtyLabel: "ปริมาณที่ใช้ (Qty)",
  miscAlertPlaceholder: "ระบุข้อความเตือน เช่น สินค้าตัวนี้ขายให้เฉพาะผู้ที่อายุ 18+ ขึ้นไปเท่านั้น",
  miscDescPlaceholder: "รายละเอียดสินค้าสำหรับระบบหลังบ้านหรือการจัดส่ง...",
  unsavedDetail: "การเปลี่ยนแปลงในฟอร์มนี้ยังไม่ได้บันทึก ถ้ายืนยัน ระบบจะปิดฟอร์มและทิ้งข้อมูลที่แก้ไขอยู่",
  discardLabel: "ทิ้งการแก้ไข",
  resizeAriaLabel: "ปรับขนาดรายการสินค้าและรายละเอียดบาร์โค้ด",

  // Competitor-grade features
  generateBarcode: "สร้างบาร์โค้ดอัตโนมัติ",
  saveAndNew: "บันทึก & เพิ่มใหม่",

  // Marketplace tabs (Shopee / Lazada / AliExpress / TikTok)
  tabMarketplace: "Marketplace",
  tabShopee: "Shopee",
  tabLazada: "Lazada",
  tabAliexpress: "AliExpress",
  tabTiktok: "TikTok",
  mkEnableOnPlatform: "ขายสินค้านี้บน %s",
  mkNotLinked: "ยังไม่ได้ผูกสินค้านี้กับ %s — เปิดสวิตช์ด้านบนเพื่อเริ่มแมพข้อมูล",
  mkSectionListing: "ข้อมูลการลงขาย",
  mkSectionMediaSpecs: "รูปภาพและข้อมูลจำเพาะ",
  mkSectionPriceStock: "ราคาและสต๊อก",
  mkSectionSync: "การซิงค์ข้อมูล",
  mkAccountId: "บัญชี/ร้านบนแพลตฟอร์ม",
  mkMarketItemId: "รหัสสินค้าบนแพลตฟอร์ม (Item ID)",
  mkMarketModelId: "รหัสตัวเลือก/รุ่น (Model/SKU ID)",
  mkItemUrl: "ลิงก์หน้าสินค้า",
  mkSellerSku: "Seller SKU (รหัสของเรา)",
  mkShopSku: "Shop SKU (แพลตฟอร์มสร้าง)",
  mkGtin: "GTIN / EAN / UPC",
  mkCategoryId: "รหัสหมวดหมู่แพลตฟอร์ม",
  mkCategoryName: "ชื่อหมวดหมู่แพลตฟอร์ม",
  mkBrandId: "รหัสยี่ห้อแพลตฟอร์ม",
  mkMediaAssets: "รูปภาพ/วิดีโอ/รูปตามตัวเลือก",
  mkSpecificationGroups: "กลุ่มข้อมูลจำเพาะ",
  mkRawAttributes: "Attribute ดิบจากช่องทางขาย",
  mkPayloadExamples: "ตัวอย่าง payload สำหรับ import/sync",
  mkJsonArrayHelp: "กรอกเป็น JSON array เพื่อให้ระบบนำเข้า/ซิงค์ได้",
  mkJsonInvalid: "JSON ไม่ถูกต้อง",
  mkCurrency: "สกุลเงิน",
  mkCustomPrice: "ราคาที่จะส่งขึ้นขาย",
  mkPlatformPrice: "ราคาจริงบนแพลตฟอร์ม",
  mkPlatformStock: "สต๊อกจริงบนแพลตฟอร์ม",
  mkSyncStock: "ซิงค์สต๊อกอัตโนมัติ",
  mkSyncPrice: "ซิงค์ราคาอัตโนมัติ",
  mkSyncEnabled: "เปิดการซิงค์",
  mkStatus: "สถานะการลงขาย",
  mkRejectReason: "เหตุผลที่ถูกปฏิเสธ/QC",
  mkDaysToShip: "วันจัดส่ง (Days to ship)",
  mkIsPreOrder: "สินค้าพรีออเดอร์",
  mkLastSyncAt: "ซิงค์ล่าสุดเมื่อ",
  mkLastSyncError: "ข้อผิดพลาดการซิงค์ล่าสุด",
  mkStatusNone: "— ยังไม่ระบุ —",
  mkStatusLive: "กำลังขาย (Live)",
  mkStatusUnlist: "ปิดการขาย (Unlist)",
  mkStatusReviewing: "รอตรวจสอบ (Reviewing)",
  mkStatusRejected: "ถูกปฏิเสธ (Rejected)",
  mkStatusDeleted: "ถูกลบ (Deleted)",
};

const barcodeTextEn: BarcodeText = {
  title: "Barcode",
  subtitle: "Manage barcodes, SKUs, selling units, prices, and product references",
  tenant: "Company",
  branch: "Branch",

  refresh: "Refresh",
  export: "Export",
  import: "Import",
  selectDelete: "Select to delete",
  cancelSelect: "Cancel selection",
  add: "Add",
  search: "Search barcode, name, or item code",
  filter: "Filter",
  sortBy: "Sort by",
  sortOrder: "Order",
  sortAsc: "Ascending",
  sortDesc: "Descending",
  showImage: "Show image",
  hideImage: "Hide image",

  groupCode: "Group",
  brandCode: "Brand",
  categoryCode: "Category",
  classCode: "Class",
  designCode: "Design",
  gradeCode: "Grade",
  modelCode: "Model",
  patternCode: "Pattern",
  priceMin: "Min price",
  priceMax: "Max price",
  clearFilter: "Clear filter",
  applyFilter: "Apply filter",

  total: "Total",
  selected: "Selected",
  barcode: "Barcode",
  productName: "Product",
  unit: "Unit",
  itemCode: "Item code",
  balance: "Balance",
  retailPrice: "Retail price",
  image: "Image",
  actions: "Actions",

  detailTitle: "Barcode detail",
  noSelection: "Select a row to see details",
  loading: "Loading barcodes",
  noData: "No barcode data",
  apiRequired: "Please sign in and pick a company",
  requestFailed: "Failed to load data",
  edit: "Edit",
  save: "Save",
  saving: "Saving…",
  close: "Close",
  cancel: "Cancel",
  createTitle: "Add barcode",
  editTitle: "Edit barcode",
  copy: "Copy",
  delete: "Delete",
  preview: "Preview",
  saveSuccess: "Barcode saved",
  deleteConfirm: "Confirm delete selected barcodes?",
  deleteSuccess: "Barcodes deleted",
  missingGuid: "No GUID to delete",
  exportSuccess: "Exported current rows",
  productMasterTitle: "Product Master",
  productMasterSubtitle: "Manage main products and link relationship with barcodes",
  productMasterSearch: "Search name or item code",
  productMasterAdd: "Add Product",
  productMasterDetailTitle: "Product Detail",
  productMasterCreateTitle: "Create New Product",
  productMasterEditTitle: "Edit Product",
  productMasterSaveSuccess: "Product saved successfully",
  productMasterDeleteConfirm: "Are you sure you want to delete this product?",
  productMasterDeleteSuccess: "Product deleted successfully",
  productMasterCodeRequired: "Item code is required",
  productMasterNameRequired: "At least one product name is required",
  codeRequired: "Item code is required",
  nameRequired: "At least one product name is required",
  manufacturers: "Manufacturers (Multiple)",
  addManufacturer: "Add Manufacturer",
  suppliers: "Suppliers/Creditors (Multiple)",
  addSupplier: "Add Supplier",
  groupsubone: "Sub Group 1",
  groupsubtwo: "Sub Group 2",
  class: "Product Class",

  bomView: "View BOM",
  priceHistory: "Price history",
  labelPrint: "Print label",

  tabBasic: "Basic",
  tabClassification: "Classification",
  tabPricing: "Pricing",
  tabStock: "Stock",
  tabUnits: "Units & Conversion",
  tabBom: "BOM",
  tabMedia: "Image & Color",
  tabRestaurant: "Restaurant / POS",
  tabTimeForSales: "Time for sales",
  tabDimensions: "Dimensions",
  tabBusinessBranch: "Business / Branch",
  tabMisc: "Other",
  tabProductDetail: "Main Product Info",

  required: "Required",
  optional: "Optional",
  barcodeHelp: "A-Z, 0-9, - only (no space)",
  names: "Names",
  product: "Main Product",
  addLanguage: "Add language",
  otherLanguage: "Other language",
  multiUnit: "Multi-unit",
  itemUnit: "Unit",
  itemUnitSize: "Unit size",
  itemType: "Item type",
  itemTypeStock: "Stock item",
  itemTypeService: "Service item",
  itemTypeSet: "Set item",
  itemTypeNotStock: "Non-stock",
  materialType: "Product Type",
  materialGeneral: "General",
  materialMaterial: "Material",
  materialSemiFinished: "Semi-finished",
  materialSet: "Set Product",
  materialAgricultural: "Agricultural Produce",
  vatType: "Tax type",
  vatIncluded: "VAT product",
  vatExcluded: "VAT exempt product",
  taxType: "Tax type",
  vatCal: "VAT calc",
  isMainBarcode: "Main barcode",
  isStock: "Track stock",

  group: "Group",
  groupSubOne: "Sub group 1",
  groupSubTwo: "Sub group 2",
  brand: "Brand",
  category: "Category",
  classification: "Class",
  design: "Design",
  grade: "Grade",
  model: "Model",
  pattern: "Pattern",
  manufacturer: "Manufacturer",
  productType: "Product type",

  prices: "Prices",
  priceKey: "Price tier",
  price: "Price",
  addPrice: "Add price tier",
  fixedCost: "Fixed cost",
  fixedCostDate: "Effective date",
  fixedCostAmount: "Cost",
  addFixedCost: "Add cost",
  discount: "Discount",
  maxDiscount: "Max discount",
  isDividend: "Dividend",
  isDiscountPointOfPurchase: "Point-of-purchase discount",

  orderPoint: "Order point",
  minPoint: "Min",
  maxPoint: "Max",
  qty: "Quantity",
  stockBarcode: "Stock barcode ref",

  divideValue: "Divide",
  standValue: "Stand",
  condition: "Condition",
  isUseSubBarcodes: "Use reference barcode",
  refBarcodes: "Reference barcodes",
  refBarcodeAdd: "Add reference barcode",
  refBarcodeQty: "Qty per unit",
  refUnitNames: "Ref unit names",

  bom: "Bill of Materials (BOM)",
  bomAdd: "Add BOM item",
  bomQty: "Qty",
  bomBarcode: "Material barcode",
  bomPreview: "Show diagram",

  useImageOrColor: "Image or color",
  imageMain: "Main image",
  imageUpload: "Upload",
  imageDelete: "Delete image",
  imageGallery: "Gallery",
  colorPick: "Pick color",
  colorName: "Color name",
  colorHex: "Color (HEX)",

  isForRestaurant: "Dine-in",
  isForTakeaway: "Take away",
  isForDelivery: "Delivery",
  isForCustomer: "Customer order",
  isForCustomerPreOrder: "Pre-order",
  isALaCarte: "à la carte",
  isStockForRestaurant: "Restaurant stock",
  isSplitUnitPrint: "Split-unit print",
  isOnlyStaff: "Staff only",
  foodType: "Food type",
  foodTypeFood: "Food",
  foodTypeDrink: "Drink",
  foodTypeAlcohol: "Alcohol",
  foodTypeOther: "Other",
  orderTypes: "Order types",
  orderTypeChargePrice: "Surcharge",
  orderTypeAdd: "Add order type",
  options: "Options",
  optionAdd: "Add option",
  optionType: "Option type",
  optionTypeMulti: "Multi-select",
  optionTypeSingle: "Single-select",
  optionMinSelect: "Min select",
  optionMaxSelect: "Max select",
  optionChoices: "Choices",
  optionChoiceAdd: "Add choice",
  optionChoicePrice: "Add price",
  optionChoiceIsStock: "Track stock",
  optionChoiceIsDefault: "Default",
  optionChoiceRefBarcode: "Ref barcode",
  optionChoiceQty: "Qty per unit",

  timeForSales: "Sales time slot",
  timeForSalesAdd: "Add slot",
  fromDate: "From date",
  toDate: "To date",
  fromTime: "From time",
  toTime: "To time",
  daysOfWeek: "Days of week",
  sun: "Sun",
  mon: "Mon",
  tue: "Tue",
  wed: "Wed",
  thu: "Thu",
  fri: "Fri",
  sat: "Sat",

  dimensions: "Dimensions",
  dimensionAdd: "Add dimension",
  dimensionGroup: "Group",
  dimensionItem: "Value",

  businessTypes: "Business types",
  businessTypeAdd: "Add business type",
  ignoreBranches: "Excluded branches",
  ignoreBranchAdd: "Add branch",
  branchHint: "Checked branches cannot sell this item",

  isSumPoint: "Reward points",
  isSumPointYes: "Accumulate points",
  isSumPointNo: "Do not accumulate points",
  isAlert: "Alert",
  alertDescription: "Alert message",
  description: "Description",
  xsorts: "Display order",
  holdingCode: "Company",
  guid: "GUID",
  refGuid: "Ref GUID",
  itemGuid: "Item GUID",

  pickerSearch: "Search",
  pickerClose: "Close",
  pickerSelect: "Select",
  pickerNoResult: "No data",
  pickerLoading: "Loading…",
  pickerClear: "Clear",

  yes: "Yes",
  no: "No",
  on: "On",
  off: "Off",
  required_error: "Required",
  invalidBarcode: "Barcode must contain only A-Z, 0-9, or -",
  unsavedChanges: "Unsaved changes — leave anyway?",

  // Detail-view section labels (barcode-screen detail panel)
  basicInfo: "Basic info",
  classificationSection: "Classification",
  stockAndUnit: "Unit, stock, and price",
  taxAndFlags: "Tax and status",
  relations: "Linked data",
  rawFields: "All API fields",

  // Extra barcode-screen field labels
  barcodeRef: "Barcode reference",
  shelf: "Shelf",
  color: "Color",
  unitCount: "Unit count",
  isMainItem: "Main item",
  subGroup1: "Sub group 1",
  subGroup2: "Sub group 2",
  subBarcodes: "Sub barcodes",
  branches: "Branches",
  categories: "Categories",
  isDisable: "Disabled",
  showIsDividend: "Dividend text",
  rowNumber: "Row number",
  itemGuidFixed: "Fixed item GUID",
  parentGuid: "Parent GUID",
  checksum: "Checksum",

  // Barcode screen dialog / confirm strings
  jsonPayload: "Full-field JSON payload",
  invalidJson: "Invalid JSON",
  deleteCurrentConfirm: "Confirm delete this barcode?",
  unsavedConfirm: "You have unsaved changes. Discard them?",

  // product-screen tab labels
  tabUnitsBarcode: "Units & Barcode",
  tabBomShort: "Components (BOM)",
  tabBusinessBranchShort: "Branch / Business",

  // product-screen inline section headers
  productTypeSection: "Product Type",
  itemTypeLabel: "Item type",
  materialTypeLabel: "Product Type",
  groupsAndCategories: "Groups & Categories",
  groupsAndCategoriesEn: "Groups & Categories",
  basicInfoCard: "Basic Info",
  groupingCard: "Grouping",
  noManufacturerData: "No manufacturer listed",
  noSupplierData: "No supplier listed",
  noManufacturerInfo: "No manufacturer data",
  noSupplierInfo: "No supplier data",
  backToList: "Back to product list",
  backToListEn: "Back to list",
  pullFromBarcode: "Pull from quick-sale barcode",
  selectUnlinkedBarcode: "Select unlinked quick-sale barcode",
  searchBarcodeOrName: "Search by barcode or product name...",
  searchingBarcode: "Searching barcodes...",
  noUnlinkedBarcode: "No unlinked barcodes found",
  allBarcodesLinked: "No orphan barcodes — all barcodes are linked to a product",
  closeWindow: "Close window",
  noName: "No name",
  unitLabel: "Unit",
  barcodeFetchSuccess: "Fetched data from barcode %s. Please verify the item code and save.",
  barcodeFetchFail: "Failed to fetch barcode detail",

  // barcode-form TabProductDetail section titles
  classificationSectionTitle: "Classifications",
  creditorsSectionTitle: "Manufacturers & Suppliers (Creditors)",
  mediaSectionTitle: "Image & Tag Color (Media)",
  restaurantSectionTitle: "Restaurant / POS Settings",
  timeSectionTitle: "Sales Time & Other",
  manufacturersLabel: "Manufacturers",
  suppliersLabel: "Suppliers",
  galleryLabel: "Image Gallery",
  noImage: "No image",
  displayMode: "Display mode",
  displayModeImage: "Show product image",
  displayModeColor: "Show tag color",
  tagColor: "Tag color",
  isForRestaurantLabel: "Dine-in",
  isForTakeawayLabel: "Take away",
  isForDeliveryLabel: "Delivery",
  isForCustomerLabel: "Customer self-order",
  isForCustomerPreOrderLabel: "Customer pre-order",
  isStockForRestaurantLabel: "Restaurant stock deduct",
  isSplitUnitPrintLabel: "Split print by unit",
  isOnlyStaffLabel: "Staff only",
  foodTypeSectionLabel: "Food type",
  optionsSectionLabel: "Options",
  optionTypeMultiLabel: "Multi-select",
  optionTypeSingleLabel: "Single-select",
  optionSelectRange: "Select %min–%max items",
  alertToggleLabel: "Alert on scan",
  alertMessageLabel: "Alert message",
  descriptionLabel: "Additional details",
  inheritedInfoBanner: "Inherited from main product:",
  inheritedInfoDetail: "Classification, creditors, images, and POS settings of this barcode are inherited from the main product",
  inheritedInfoEditHint: "To edit these fields, go to menu",
  productMenuName: "Products",
  loadingProductDetail: "Loading main product details...",
  noProductDetailFound: "Main product not found. Please check the product link in the Basic tab.",

  // product-screen sub-component labels (media, units, BOM, options, time, business, misc)
  mediaUseSection: "Image or tag color",
  mediaMainSection: "Main product image",
  mediaGallerySection: "Image gallery",
  mediaAddGallery: "Add gallery image",
  mediaColorSection: "Tag color",
  mediaUploading: "Uploading...",
  mediaUploadBtn: "Upload image",
  mediaDeleteBtn: "Delete image",
  mediaNoGallery: "— No gallery images —",
  mediaColorName: "Color name",
  mediaColorHex: "Tag color (Hex)",
  mediaNoImage: "No image",
  optionGroupName: "Option group name",
  optionChoiceType: "Choice type",
  optionChoiceTypeMulti: "Multi-select (Checkbox)",
  optionChoiceTypeSingle: "Single-select (Radio)",
  optionMinSelectLabel: "Min select",
  optionMaxSelectLabel: "Max select",
  optionChoiceName: "Choice name",
  optionChoicePriceLabel: "Add-on price",
  optionChoiceQtyLabel: "Quantity",
  optionChoiceDefaultLabel: "Default choice",
  optionChoiceStockLabel: "Deduct stock",
  optionAddGroup: "Add option group",
  optionAddChoice: "Add choice",
  optionGroupNo: "Option group #",
  optionChoiceNo: "Choice #",
  optionChoiceList: "Choices",
  timeSection: "Sales time slot settings",
  timeAddBtn: "Add time slot",
  timeNoLimit: "— This product can be sold at any time —",
  timeDaysLabel: "Days of week",
  timeRuleNo: "Time rule #",
  timeFromDate: "From date",
  timeToDate: "To date",
  timeFromTime: "From time",
  timeToTime: "To time",
  businessTypeSection: "Excluded by business type",
  businessTypeAddBtn: "Add excluded business type",
  businessTypeNoData: "— No exclusions — available for all business types —",
  branchSection: "Branches excluded from selling this item",
  branchAddBtn: "Add excluded branch",
  branchHintDetail: "Branches added here cannot scan or check stock of this item",
  branchNoData: "— No excluded branches — available in all branches —",
  pickerBranch: "Branch",
  pickerBusinessType: "Business type",
  miscAlertSection: "Pop-up alert on POS",
  miscAlertToggle: "Enable alert on scan",
  miscAlertDetail: "Alert message detail",
  miscDescSection: "Product description / additional details",
  miscGuidSection: "ID / GUID reference",
  miscGuidFixed: "Product GUID Fixed",
  miscHoldingCode: "Holding Code",
  miscUnitGuid: "Base unit GUID",
  unitSection: "Unit & conversion ratio",
  unitBaseUnit: "Base unit",
  unitBasePlaceholder: "Click to select base unit...",
  unitDivide: "Divide value",
  unitStand: "Stand value",
  unitCondition: "Has unit condition",
  unitConditionEnable: "Enable",
  unitMultiSection: "Multi-unit barcode management",
  unitMultiToggle: "Enable multi-unit barcodes",
  unitRefListTitle: "Supplementary unit barcodes",
  unitRefAddBtn: "Add supplementary barcode",
  unitRefNoData: "No supplementary unit barcodes",
  unitRefBarcode: "Barcode",
  unitRefBarcodePlaceholder: "Enter sub-unit barcode",
  unitRefUnitCode: "Unit code",
  unitRefUnitPlaceholder: "e.g. PCS, BOX",
  unitRefQty: "Sub-unit qty",
  unitRefDivide: "Divide",
  unitRefStand: "Stand",
  bomSection: "Bill of Materials (BOM)",
  bomAddBtn: "Add material",
  bomNoData: "No materials in BOM",
  bomBarcodeLabel: "Material barcode",
  bomBarcodePlaceholder: "Scan or type material barcode",
  bomUnitLabel: "Material unit",
  bomUnitPlaceholder: "e.g. PCS, KG",
  bomQtyLabel: "Qty used",
  miscAlertPlaceholder: "Enter alert message, e.g. Age 18+ only",
  miscDescPlaceholder: "Product description for back-office or delivery...",
  unsavedDetail: "Changes in this form are not yet saved. If you confirm, the form will close and edits will be discarded.",
  discardLabel: "Discard changes",
  resizeAriaLabel: "Resize product list and barcode detail panels",

  // Competitor-grade features
  generateBarcode: "Generate barcode",
  saveAndNew: "Save & add new",

  // Marketplace tabs (Shopee / Lazada / AliExpress / TikTok)
  tabMarketplace: "Marketplace",
  tabShopee: "Shopee",
  tabLazada: "Lazada",
  tabAliexpress: "AliExpress",
  tabTiktok: "TikTok",
  mkEnableOnPlatform: "Sell this item on %s",
  mkNotLinked: "Not linked to %s yet — turn on the switch above to start mapping",
  mkSectionListing: "Listing info",
  mkSectionMediaSpecs: "Images & specifications",
  mkSectionPriceStock: "Price & stock",
  mkSectionSync: "Sync",
  mkAccountId: "Platform account/shop",
  mkMarketItemId: "Platform item ID",
  mkMarketModelId: "Variation/Model (SKU) ID",
  mkItemUrl: "Listing URL",
  mkSellerSku: "Seller SKU (ours)",
  mkShopSku: "Shop SKU (platform-generated)",
  mkGtin: "GTIN / EAN / UPC",
  mkCategoryId: "Platform category ID",
  mkCategoryName: "Platform category name",
  mkBrandId: "Platform brand ID",
  mkMediaAssets: "Images/videos/variation media",
  mkSpecificationGroups: "Specification groups",
  mkRawAttributes: "Raw channel attributes",
  mkPayloadExamples: "Import/sync payload examples",
  mkJsonArrayHelp: "Use a JSON array so the system can import/sync it.",
  mkJsonInvalid: "Invalid JSON",
  mkCurrency: "Currency",
  mkCustomPrice: "Price to publish",
  mkPlatformPrice: "Actual price on platform",
  mkPlatformStock: "Actual stock on platform",
  mkSyncStock: "Auto-sync stock",
  mkSyncPrice: "Auto-sync price",
  mkSyncEnabled: "Enable sync",
  mkStatus: "Listing status",
  mkRejectReason: "Reject / QC reason",
  mkDaysToShip: "Days to ship",
  mkIsPreOrder: "Pre-order item",
  mkLastSyncAt: "Last synced at",
  mkLastSyncError: "Last sync error",
  mkStatusNone: "— Not set —",
  mkStatusLive: "Live",
  mkStatusUnlist: "Unlist",
  mkStatusReviewing: "Reviewing",
  mkStatusRejected: "Rejected",
  mkStatusDeleted: "Deleted",
};

const dict: Record<LanguageCode, BarcodeText> = {
  th: barcodeTextTh,
  en: barcodeTextEn,
  cn: barcodeTextEn,
  ja: barcodeTextEn,
  ko: barcodeTextEn,
  lo: barcodeTextTh,
  my: barcodeTextEn,
  km: barcodeTextEn,
  vi: barcodeTextEn,
  ms: barcodeTextEn,
  id: barcodeTextEn,
  fil: barcodeTextEn,
};

export function getBarcodeText(language: LanguageCode | string | undefined): BarcodeText {
  return dict[normalizeLanguage(language)] ?? barcodeTextTh;
}
