/**
 * UI string pack for Product Barcode screens.
 *
 * Source of truth note:
 * backend `assets/language/languages.tsv` is the canonical label registry.
 * The keys below should eventually be backed by language API; until those keys
 * land in TSV we keep a local Thai/English fallback so the screen ships.
 * Each key here SHOULD have a matching entry in TSV — see
 * `backend/prompts/language_requests/product-barcode-screen.md` for batch.
 */

import { type LanguageCode, normalizeLanguage } from "@/lib/i18n";

export type BarcodeText = typeof barcodeTextTh;

const barcodeTextTh = {
  // Page
  title: "สินค้า",
  subtitle: "จัดการสินค้าและข้อมูลที่เกี่ยวข้องทั้งหมด",
  tenant: "บริษัท",
  branch: "สาขา",

  // Toolbar
  refresh: "รีเฟรช",
  export: "ส่งออก",
  import: "นำเข้า",
  selectDelete: "เลือกเพื่อลบ",
  cancelSelect: "ยกเลิกเลือก",
  add: "เพิ่ม",
  search: "ค้นหา บาร์โค้ด ชื่อสินค้า หรือรหัสสินค้า",
  filter: "ตัวกรอง",
  sortBy: "เรียงตาม",
  sortOrder: "ลำดับ",
  sortAsc: "น้อย → มาก",
  sortDesc: "มาก → น้อย",
  showImage: "แสดงรูป",
  hideImage: "ซ่อนรูป",

  // Filter fields
  groupCode: "กลุ่มสินค้า",
  brandCode: "ยี่ห้อ",
  categoryCode: "หมวดสินค้า",
  classCode: "Class",
  designCode: "Design",
  gradeCode: "Grade",
  modelCode: "Model",
  patternCode: "Pattern",
  priceMin: "ราคาต่ำสุด",
  priceMax: "ราคาสูงสุด",
  clearFilter: "ล้างตัวกรอง",
  applyFilter: "ใช้ตัวกรอง",

  // List columns
  total: "ทั้งหมด",
  selected: "เลือกแล้ว",
  barcode: "บาร์โค้ด",
  productName: "ชื่อสินค้า",
  unit: "หน่วย",
  itemCode: "รหัสสินค้า",
  balance: "คงเหลือ",
  retailPrice: "ราคาขาย",
  image: "รูป",
  actions: "การจัดการ",

  // Detail / Form
  detailTitle: "รายละเอียดบาร์โค้ด",
  noSelection: "เลือกรายการด้านซ้ายเพื่อดูรายละเอียด",
  loading: "กำลังโหลดข้อมูลบาร์โค้ด",
  noData: "ไม่พบข้อมูลบาร์โค้ด",
  apiRequired: "กรุณาเข้าสู่ระบบและเลือกบริษัทก่อนเปิดหน้าจอนี้",
  requestFailed: "โหลดข้อมูลไม่สำเร็จ",
  edit: "แก้ไข",
  save: "บันทึก",
  saving: "กำลังบันทึก…",
  close: "ปิด",
  cancel: "ยกเลิก",
  createTitle: "เพิ่มสินค้า",
  editTitle: "แก้ไขสินค้า",
  copy: "คัดลอก",
  delete: "ลบ",
  preview: "ตัวอย่าง",
  saveSuccess: "บันทึกสินค้าแล้ว",
  deleteConfirm: "ต้องการลบสินค้าที่เลือกจริงหรือไม่",
  deleteSuccess: "ลบสินค้าแล้ว",
  missingGuid: "รายการที่เลือกไม่มี GUID สำหรับลบ",
  exportSuccess: "ส่งออกข้อมูลที่แสดงอยู่แล้ว",

  // Quick actions
  bomView: "ดูสูตรการผลิต",
  priceHistory: "ประวัติราคา",
  labelPrint: "พิมพ์ป้ายสินค้า",

  // Tabs
  tabBasic: "ข้อมูลหลัก",
  tabClassification: "หมวดหมู่",
  tabPricing: "ราคา",
  tabStock: "คงคลัง",
  tabUnits: "หน่วยและการแปลง",
  tabBom: "สูตรการผลิต (BOM)",
  tabMedia: "ภาพและสี",
  tabRestaurant: "ร้านอาหาร/POS",
  tabTimeForSales: "เวลาขาย",
  tabDimensions: "ขนาด",
  tabBusinessBranch: "ธุรกิจ/สาขา",
  tabMisc: "อื่นๆ",

  // Basic tab
  required: "จำเป็น",
  optional: "ไม่บังคับ",
  barcodeHelp: "เฉพาะ A-Z, 0-9, - (ไม่เว้นวรรค)",
  names: "ชื่อสินค้า",
  addLanguage: "เพิ่มภาษาอื่น",
  otherLanguage: "ภาษาอื่น",
  multiUnit: "หลายหน่วย",
  itemUnit: "หน่วยนับ",
  itemUnitSize: "ขนาดต่อหน่วย",
  itemType: "ประเภทสินค้า",
  itemTypeStock: "สินค้ามีสต๊อก",
  itemTypeService: "ประเภทสินค้าบริการ",
  itemTypeSet: "สินค้าชุด",
  itemTypeNotStock: "ไม่ตัดสต๊อก",
  materialType: "ประเภทวัตถุดิบ",
  materialGeneral: "สินค้าทั่วไป",
  materialMaterial: "วัตถุดิบ",
  materialSemiFinished: "กึ่งสำเร็จรูป",
  vatType: "ประเภทภาษี",
  vatIncluded: "สินค้ามีภาษีมูลค่าเพิ่ม",
  vatExcluded: "สินค้ายกเว้นภาษีมูลค่าเพิ่ม",
  taxType: "ประเภทภาษี",
  vatCal: "วิธีคำนวณ VAT",
  isMainBarcode: "บาร์โค้ดหลัก",
  isStock: "ตัดสต๊อก",

  // Classification tab
  group: "กลุ่มสินค้า",
  groupSubOne: "หมวดย่อย 1",
  groupSubTwo: "หมวดย่อย 2",
  brand: "ยี่ห้อ",
  category: "หมวดสินค้า",
  classification: "Class",
  design: "Design",
  grade: "เกรด",
  model: "Model",
  pattern: "Pattern",
  manufacturer: "ผู้ผลิต",
  productType: "ประเภทสินค้า (POS)",

  // Pricing tab
  prices: "ราคาขาย",
  priceKey: "ระดับราคา",
  price: "ราคา",
  addPrice: "เพิ่มระดับราคา",
  fixedCost: "ต้นทุนมาตรฐาน",
  fixedCostDate: "วันที่มีผล",
  fixedCostAmount: "ต้นทุน",
  addFixedCost: "เพิ่มต้นทุน",
  discount: "ส่วนลด",
  maxDiscount: "ส่วนลดสูงสุด",
  isDividend: "ใช้สิทธิ์ปันผล",
  isDiscountPointOfPurchase: "ส่วนลด ณ จุดขาย",

  // Stock tab
  orderPoint: "Order Point",
  minPoint: "Min",
  maxPoint: "Max",
  qty: "จำนวนคงเหลือ",
  stockBarcode: "Barcode อ้างอิงสต๊อก",

  // Units tab
  divideValue: "ตัวหาร (Divide)",
  standValue: "ค่ามาตรฐาน (Stand)",
  condition: "Condition",
  isUseSubBarcodes: "ใช้บาร์โค้ดอ้างอิง",
  refBarcodes: "บาร์โค้ดอ้างอิง",
  refBarcodeAdd: "เพิ่มบาร์โค้ดอ้างอิง",
  refBarcodeQty: "จำนวนต่อหน่วย",
  refUnitNames: "หน่วยอ้างอิง",

  // BOM tab
  bom: "สูตรการผลิต (BOM)",
  bomAdd: "เพิ่มรายการ",
  bomQty: "จำนวน",
  bomBarcode: "บาร์โค้ดวัตถุดิบ",
  bomPreview: "ดูแผนภาพ",

  // Media tab
  useImageOrColor: "ใช้รูปภาพหรือสี",
  imageMain: "รูปหลัก",
  imageUpload: "อัปโหลดรูป",
  imageDelete: "ลบรูป",
  imageGallery: "รูปเพิ่มเติม",
  colorPick: "เลือกสี",
  colorName: "ชื่อสี",
  colorHex: "รหัสสี (HEX)",

  // Restaurant tab
  isForRestaurant: "ทานที่ร้าน",
  isForTakeaway: "สั่งกลับบ้าน",
  isForDelivery: "เดลิเวอรี่",
  isForCustomer: "ลูกค้าสั่งได้",
  isForCustomerPreOrder: "Pre-order",
  isALaCarte: "à la carte",
  isStockForRestaurant: "ตัดสต๊อกสำหรับร้านอาหาร",
  isSplitUnitPrint: "แยกพิมพ์ตามหน่วย",
  isOnlyStaff: "เฉพาะพนักงาน",
  foodType: "ประเภทอาหาร",
  foodTypeFood: "อาหาร",
  foodTypeDrink: "เครื่องดื่ม",
  foodTypeAlcohol: "แอลกอฮอล์",
  foodTypeOther: "อื่นๆ",
  orderTypes: "ประเภทการสั่ง",
  orderTypeChargePrice: "ราคาเพิ่ม",
  orderTypeAdd: "เพิ่มประเภทการสั่ง",
  options: "ตัวเลือกเสริม",
  optionAdd: "เพิ่มตัวเลือก",
  optionType: "ชนิดตัวเลือก",
  optionTypeMulti: "เลือกได้หลายอย่าง",
  optionTypeSingle: "เลือกได้หนึ่งอย่าง",
  optionMinSelect: "เลือกอย่างน้อย",
  optionMaxSelect: "เลือกได้สูงสุด",
  optionChoices: "ตัวเลือก",
  optionChoiceAdd: "เพิ่มตัวเลือก",
  optionChoicePrice: "ราคาเพิ่ม",
  optionChoiceIsStock: "ตัดสต๊อก",
  optionChoiceIsDefault: "เลือกโดยปริยาย",
  optionChoiceRefBarcode: "บาร์โค้ดอ้างอิง",
  optionChoiceQty: "จำนวนต่อหน่วย",

  // TimeForSales tab
  timeForSales: "ช่วงเวลาที่ขายได้",
  timeForSalesAdd: "เพิ่มช่วงเวลา",
  fromDate: "ตั้งแต่วันที่",
  toDate: "ถึงวันที่",
  fromTime: "ตั้งแต่เวลา",
  toTime: "ถึงเวลา",
  daysOfWeek: "วันในสัปดาห์",
  sun: "อา",
  mon: "จ",
  tue: "อ",
  wed: "พ",
  thu: "พฤ",
  fri: "ศ",
  sat: "ส",

  // Dimensions tab
  dimensions: "ขนาด",
  dimensionAdd: "เพิ่มขนาด",
  dimensionGroup: "หมวดขนาด",
  dimensionItem: "ค่า",

  // Business / Branch tab
  businessTypes: "ประเภทธุรกิจ",
  businessTypeAdd: "เพิ่มประเภทธุรกิจ",
  ignoreBranches: "สาขาที่ไม่ขาย",
  ignoreBranchAdd: "เพิ่มสาขา",
  branchHint: "สาขาที่ติ๊กจะไม่สามารถขายสินค้านี้ได้",

  // Misc tab
  isSumPoint: "คะแนนสะสม",
  isSumPointYes: "คิดคะแนนสะสม",
  isSumPointNo: "ไม่คิดคะแนนสะสม",
  isAlert: "แจ้งเตือน",
  alertDescription: "ข้อความแจ้งเตือน",
  description: "หมายเหตุ / รายละเอียด",
  xsorts: "ลำดับการแสดงผล",
  shopId: "บริษัท",
  guid: "GUID",
  refGuid: "GUID อ้างอิง",
  itemGuid: "GUID สินค้า",

  // Picker
  pickerSearch: "ค้นหา",
  pickerClose: "ปิด",
  pickerSelect: "เลือก",
  pickerNoResult: "ไม่พบข้อมูล",
  pickerLoading: "กำลังโหลด…",
  pickerClear: "ล้างค่า",

  // Common
  yes: "ใช่",
  no: "ไม่",
  on: "เปิด",
  off: "ปิด",
  required_error: "จำเป็นต้องระบุ",
  invalidBarcode: "บาร์โค้ดต้องเป็น A-Z, 0-9 หรือ - เท่านั้น",
  unsavedChanges: "มีการแก้ไขที่ยังไม่บันทึก ต้องการออกหรือไม่?",
};

const barcodeTextEn: BarcodeText = {
  title: "Product",
  subtitle: "Manage products and related data",
  tenant: "Company",
  branch: "Branch",

  refresh: "Refresh",
  export: "Export",
  import: "Import",
  selectDelete: "Select to delete",
  cancelSelect: "Cancel selection",
  add: "Add",
  search: "Search barcode, name, or item code",
  filter: "Filter",
  sortBy: "Sort by",
  sortOrder: "Order",
  sortAsc: "Ascending",
  sortDesc: "Descending",
  showImage: "Show image",
  hideImage: "Hide image",

  groupCode: "Group",
  brandCode: "Brand",
  categoryCode: "Category",
  classCode: "Class",
  designCode: "Design",
  gradeCode: "Grade",
  modelCode: "Model",
  patternCode: "Pattern",
  priceMin: "Min price",
  priceMax: "Max price",
  clearFilter: "Clear filter",
  applyFilter: "Apply filter",

  total: "Total",
  selected: "Selected",
  barcode: "Barcode",
  productName: "Product",
  unit: "Unit",
  itemCode: "Item code",
  balance: "Balance",
  retailPrice: "Retail price",
  image: "Image",
  actions: "Actions",

  detailTitle: "Barcode detail",
  noSelection: "Select a row to see details",
  loading: "Loading barcodes",
  noData: "No barcode data",
  apiRequired: "Please sign in and pick a company",
  requestFailed: "Failed to load data",
  edit: "Edit",
  save: "Save",
  saving: "Saving…",
  close: "Close",
  cancel: "Cancel",
  createTitle: "Add product",
  editTitle: "Edit product",
  copy: "Copy",
  delete: "Delete",
  preview: "Preview",
  saveSuccess: "Product saved",
  deleteConfirm: "Confirm delete selected products?",
  deleteSuccess: "Products deleted",
  missingGuid: "No GUID to delete",
  exportSuccess: "Exported current rows",

  bomView: "View BOM",
  priceHistory: "Price history",
  labelPrint: "Print label",

  tabBasic: "Basic",
  tabClassification: "Classification",
  tabPricing: "Pricing",
  tabStock: "Stock",
  tabUnits: "Units & Conversion",
  tabBom: "BOM",
  tabMedia: "Image & Color",
  tabRestaurant: "Restaurant / POS",
  tabTimeForSales: "Time for sales",
  tabDimensions: "Dimensions",
  tabBusinessBranch: "Business / Branch",
  tabMisc: "Other",

  required: "Required",
  optional: "Optional",
  barcodeHelp: "A-Z, 0-9, - only (no space)",
  names: "Names",
  addLanguage: "Add language",
  otherLanguage: "Other language",
  multiUnit: "Multi-unit",
  itemUnit: "Unit",
  itemUnitSize: "Unit size",
  itemType: "Item type",
  itemTypeStock: "Stock item",
  itemTypeService: "Service item",
  itemTypeSet: "Set item",
  itemTypeNotStock: "Non-stock",
  materialType: "Material type",
  materialGeneral: "General",
  materialMaterial: "Material",
  materialSemiFinished: "Semi-finished",
  vatType: "Tax type",
  vatIncluded: "VAT product",
  vatExcluded: "VAT exempt product",
  taxType: "Tax type",
  vatCal: "VAT calc",
  isMainBarcode: "Main barcode",
  isStock: "Track stock",

  group: "Group",
  groupSubOne: "Sub group 1",
  groupSubTwo: "Sub group 2",
  brand: "Brand",
  category: "Category",
  classification: "Class",
  design: "Design",
  grade: "Grade",
  model: "Model",
  pattern: "Pattern",
  manufacturer: "Manufacturer",
  productType: "Product type",

  prices: "Prices",
  priceKey: "Price tier",
  price: "Price",
  addPrice: "Add price tier",
  fixedCost: "Fixed cost",
  fixedCostDate: "Effective date",
  fixedCostAmount: "Cost",
  addFixedCost: "Add cost",
  discount: "Discount",
  maxDiscount: "Max discount",
  isDividend: "Dividend",
  isDiscountPointOfPurchase: "Point-of-purchase discount",

  orderPoint: "Order point",
  minPoint: "Min",
  maxPoint: "Max",
  qty: "Quantity",
  stockBarcode: "Stock barcode ref",

  divideValue: "Divide",
  standValue: "Stand",
  condition: "Condition",
  isUseSubBarcodes: "Use reference barcode",
  refBarcodes: "Reference barcodes",
  refBarcodeAdd: "Add reference barcode",
  refBarcodeQty: "Qty per unit",
  refUnitNames: "Ref unit names",

  bom: "Bill of Materials (BOM)",
  bomAdd: "Add BOM item",
  bomQty: "Qty",
  bomBarcode: "Material barcode",
  bomPreview: "Show diagram",

  useImageOrColor: "Image or color",
  imageMain: "Main image",
  imageUpload: "Upload",
  imageDelete: "Delete image",
  imageGallery: "Gallery",
  colorPick: "Pick color",
  colorName: "Color name",
  colorHex: "Color (HEX)",

  isForRestaurant: "Dine-in",
  isForTakeaway: "Take away",
  isForDelivery: "Delivery",
  isForCustomer: "Customer order",
  isForCustomerPreOrder: "Pre-order",
  isALaCarte: "à la carte",
  isStockForRestaurant: "Restaurant stock",
  isSplitUnitPrint: "Split-unit print",
  isOnlyStaff: "Staff only",
  foodType: "Food type",
  foodTypeFood: "Food",
  foodTypeDrink: "Drink",
  foodTypeAlcohol: "Alcohol",
  foodTypeOther: "Other",
  orderTypes: "Order types",
  orderTypeChargePrice: "Surcharge",
  orderTypeAdd: "Add order type",
  options: "Options",
  optionAdd: "Add option",
  optionType: "Option type",
  optionTypeMulti: "Multi-select",
  optionTypeSingle: "Single-select",
  optionMinSelect: "Min select",
  optionMaxSelect: "Max select",
  optionChoices: "Choices",
  optionChoiceAdd: "Add choice",
  optionChoicePrice: "Add price",
  optionChoiceIsStock: "Track stock",
  optionChoiceIsDefault: "Default",
  optionChoiceRefBarcode: "Ref barcode",
  optionChoiceQty: "Qty per unit",

  timeForSales: "Sales time slot",
  timeForSalesAdd: "Add slot",
  fromDate: "From date",
  toDate: "To date",
  fromTime: "From time",
  toTime: "To time",
  daysOfWeek: "Days of week",
  sun: "Sun",
  mon: "Mon",
  tue: "Tue",
  wed: "Wed",
  thu: "Thu",
  fri: "Fri",
  sat: "Sat",

  dimensions: "Dimensions",
  dimensionAdd: "Add dimension",
  dimensionGroup: "Group",
  dimensionItem: "Value",

  businessTypes: "Business types",
  businessTypeAdd: "Add business type",
  ignoreBranches: "Excluded branches",
  ignoreBranchAdd: "Add branch",
  branchHint: "Checked branches cannot sell this item",

  isSumPoint: "Reward points",
  isSumPointYes: "Accumulate points",
  isSumPointNo: "Do not accumulate points",
  isAlert: "Alert",
  alertDescription: "Alert message",
  description: "Description",
  xsorts: "Display order",
  shopId: "Company",
  guid: "GUID",
  refGuid: "Ref GUID",
  itemGuid: "Item GUID",

  pickerSearch: "Search",
  pickerClose: "Close",
  pickerSelect: "Select",
  pickerNoResult: "No data",
  pickerLoading: "Loading…",
  pickerClear: "Clear",

  yes: "Yes",
  no: "No",
  on: "On",
  off: "Off",
  required_error: "Required",
  invalidBarcode: "Barcode must contain only A-Z, 0-9, or -",
  unsavedChanges: "Unsaved changes — leave anyway?",
};

const dict: Record<LanguageCode, BarcodeText> = {
  th: barcodeTextTh,
  en: barcodeTextEn,
  cn: barcodeTextEn,
  ja: barcodeTextEn,
  ko: barcodeTextEn,
  lo: barcodeTextTh,
  my: barcodeTextEn,
  km: barcodeTextEn,
  vi: barcodeTextEn,
  ms: barcodeTextEn,
  id: barcodeTextEn,
  fil: barcodeTextEn,
};

export function getBarcodeText(language: LanguageCode | string | undefined): BarcodeText {
  return dict[normalizeLanguage(language)] ?? barcodeTextTh;
}
