"use client";

import { useState, useMemo } from "react";
import {
  getErpReportConfig,
  getSampleReportData,
} from "@/lib/erp-reports";
import type { LanguageCode } from "@/lib/i18n";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import {
  BarChart3,
  Download,
  Printer,
  Calendar,
  Search,
  ArrowUpDown,
  FileCode,
  Layers,
} from "lucide-react";

interface ErpReportViewerProps {
  route: string;
  embedded?: boolean;
  language?: LanguageCode;
}

export function ErpReportViewer({
  route,
  embedded: _embedded = false,
  language = "th",
}: ErpReportViewerProps) {
  const config = getErpReportConfig(route) || {
    route,
    code: "report_viewer",
    category: "inventory" as const,
    title: { th: "รายงานระบบ ERP", en: "ERP Report Viewer" },
    description: { th: "รายงานสรุปและวิเคราะห์ข้อมูลธุรกิจ", en: "Business Analytics & Report" },
    defaultSortKey: "",
    columns: [],
  };

  const [searchTerm, setSearchTerm] = useState<string>("");
  const [sortKey, setSortKey] = useState<string>(config.defaultSortKey);
  const [sortAsc, setSortAsc] = useState<boolean>(true);
  const [dateRange, setDateRange] = useState<string>("month");

  const rawData = useMemo(() => getSampleReportData(config.code), [config.code]);

  // Filtered & Sorted Data
  const processedData = useMemo(() => {
    let result = [...rawData];

    if (searchTerm.trim()) {
      const term = searchTerm.toLowerCase();
      result = result.filter((row) =>
        Object.values(row).some((val) =>
          String(val ?? "").toLowerCase().includes(term),
        ),
      );
    }

    if (sortKey) {
      result.sort((a, b) => {
        const valA = a[sortKey];
        const valB = b[sortKey];
        if (typeof valA === "number" && typeof valB === "number") {
          return sortAsc ? valA - valB : valB - valA;
        }
        return sortAsc
          ? String(valA ?? "").localeCompare(String(valB ?? ""))
          : String(valB ?? "").localeCompare(String(valA ?? ""));
      });
    }

    return result;
  }, [rawData, searchTerm, sortKey, sortAsc]);

  // Totals for numeric columns
  const columnTotals = useMemo(() => {
    const totals: Record<string, number> = {};
    for (const col of config.columns) {
      if (col.isNumeric || col.isCurrency) {
        totals[col.key] = processedData.reduce(
          (sum, row) => sum + (Number(row[col.key]) || 0),
          0,
        );
      }
    }
    return totals;
  }, [config.columns, processedData]);

  function handleSort(key: string) {
    if (sortKey === key) {
      setSortAsc(!sortAsc);
    } else {
      setSortKey(key);
      setSortAsc(true);
    }
  }

  function handleExportCsv() {
    const headers = config.columns.map((col) => (language === "th" ? col.label.th : col.label.en));
    const rows = processedData.map((row) =>
      config.columns.map((col) => `"${row[col.key] ?? ""}"`).join(","),
    );
    const csvContent = [headers.join(","), ...rows].join("\n");
    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `${config.code}_report.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }

  function handleExportXbrl() {
    const xml = `<?xml version="1.0" encoding="utf-8"?>
<xbrli:xbrl xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:th-gaap-ci="http://www.dbd.go.th/2026/th-gaap-ci">
  <!-- Thai DBD e-Filing XBRL Financial Statement Taxonomy (Auto-generated by BC Ai Account) -->
  <xbrli:context id="CurrentPeriod">
    <xbrli:entity>
      <xbrli:identifier scheme="http://www.dbd.go.th">0105558001234</xbrli:identifier>
    </xbrli:entity>
    <xbrli:period>
      <xbrli:startDate>2026-01-01</xbrli:startDate>
      <xbrli:endDate>2026-12-31</xbrli:endDate>
    </xbrli:period>
  </xbrli:context>
  ${processedData
    .map(
      (item) =>
        `<${item.xbrltag} contextRef="CurrentPeriod" decimals="2" unitRef="THB">${item.amount}</${item.xbrltag}>`,
    )
    .join("\n  ")}
</xbrli:xbrl>`;

    const blob = new Blob([xml], { type: "application/xml;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `dbd_efiling_${config.code}.xml`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }

  return (
    <div className="flex flex-col gap-4 p-4 lg:p-6">
      {/* Header Bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-border bg-card p-4 shadow-sm">
        <div className="flex items-center gap-3">
          <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 text-primary">
            {config.category === "xbrl" ? <FileCode className="h-6 w-6" /> : <BarChart3 className="h-6 w-6" />}
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-xl font-bold text-foreground">
                {language === "th" ? config.title.th : config.title.en}
              </h1>
              <span className="rounded-md bg-primary/10 px-2 py-0.5 text-xs font-semibold text-primary uppercase">
                {config.category}
              </span>
            </div>
            <p className="text-sm text-muted-foreground">
              {language === "th" ? config.description.th : config.description.en}
            </p>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          {config.category === "xbrl" && (
            <Button variant="default" onClick={handleExportXbrl} className="gap-2 bg-emerald-600 hover:bg-emerald-700">
              <FileCode className="h-4 w-4" />
              {language === "th" ? "ส่งออก XBRL (ยื่น DBD)" : "Export DBD XBRL"}
            </Button>
          )}

          <Button variant="outline" onClick={handleExportCsv} className="gap-2">
            <Download className="h-4 w-4" />
            {language === "th" ? "ส่งออก CSV" : "Export CSV"}
          </Button>

          <Button variant="outline" onClick={() => window.print()} className="gap-2">
            <Printer className="h-4 w-4" />
            {language === "th" ? "พิมพ์รายงาน" : "Print Report"}
          </Button>
        </div>
      </div>

      {/* Filter and Date Control Bar */}
      <Card>
        <CardContent className="flex flex-wrap items-center justify-between gap-4 p-4">
          <div className="flex flex-wrap items-center gap-2">
            <div className="flex items-center gap-2 text-sm font-medium text-muted-foreground mr-2">
              <Calendar className="h-4 w-4 text-primary" />
              <span>{language === "th" ? "ช่วงเวลา:" : "Period:"}</span>
            </div>
            {(["today", "week", "month", "year"] as const).map((period) => (
              <Button
                key={period}
                size="sm"
                variant={dateRange === period ? "default" : "outline"}
                onClick={() => setDateRange(period)}
                className="h-8 text-xs"
              >
                {period === "today" && (language === "th" ? "วันนี้" : "Today")}
                {period === "week" && (language === "th" ? "สัปดาห์นี้" : "This Week")}
                {period === "month" && (language === "th" ? "เดือนนี้" : "This Month")}
                {period === "year" && (language === "th" ? "ปีนี้" : "This Year")}
              </Button>
            ))}

            <div className="ml-3 flex items-center gap-1.5 rounded-lg bg-muted px-3 py-1 text-xs text-muted-foreground">
              <Layers className="h-3.5 w-3.5" />
              <span>ทุกสาขา (All Branches)</span>
            </div>
          </div>

          <div className="relative w-full max-w-xs">
            <Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder={language === "th" ? "ค้นหาในรายงาน..." : "Search in report..."}
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-9 h-9"
            />
          </div>
        </CardContent>
      </Card>

      {/* Report Data Table */}
      <Card className="overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead className="border-b bg-muted/60 text-xs font-semibold text-muted-foreground uppercase">
              <tr>
                <th className="px-3 py-3 w-12 text-center">ลำดับ</th>
                {config.columns.map((col) => (
                  <th
                    key={col.key}
                    className={`px-4 py-3 cursor-pointer select-none hover:bg-muted/80 transition-colors ${
                      col.align === "right"
                        ? "text-right"
                        : col.align === "center"
                          ? "text-center"
                          : "text-left"
                    }`}
                    onClick={() => handleSort(col.key)}
                  >
                    <div className={`flex items-center gap-1.5 ${col.align === "right" ? "justify-end" : col.align === "center" ? "justify-center" : "justify-start"}`}>
                      <span>{language === "th" ? col.label.th : col.label.en}</span>
                      <ArrowUpDown className="h-3 w-3 opacity-60" />
                    </div>
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {processedData.length === 0 ? (
                <tr>
                  <td colSpan={config.columns.length + 1} className="py-12 text-center text-muted-foreground">
                    {language === "th" ? "ไม่พบข้อมูลที่ตรงกับเงื่อนไขการค้นหา" : "No matching records found"}
                  </td>
                </tr>
              ) : (
                processedData.map((row, idx) => (
                  <tr key={idx} className="hover:bg-muted/30 transition-colors">
                    <td className="px-3 py-2.5 text-center text-muted-foreground font-mono text-xs">{idx + 1}</td>
                    {config.columns.map((col) => {
                      const val = row[col.key];
                      return (
                        <td
                          key={col.key}
                          className={`px-4 py-2.5 ${
                            col.align === "right"
                              ? "text-right font-mono"
                              : col.align === "center"
                                ? "text-center"
                                : "text-left"
                          } ${col.isCurrency ? "font-medium" : ""}`}
                        >
                          {col.isCurrency && typeof val === "number"
                            ? val.toLocaleString("th-TH", { minimumFractionDigits: 2 })
                            : col.isNumeric && typeof val === "number"
                              ? val.toLocaleString("th-TH")
                              : String(val ?? "-")}
                        </td>
                      );
                    })}
                  </tr>
                ))
              )}
            </tbody>
            {processedData.length > 0 && (
              <tfoot className="border-t-2 bg-muted/40 font-bold">
                <tr>
                  <td className="px-3 py-3 text-center text-xs">รวม</td>
                  {config.columns.map((col, idx) => {
                    const total = columnTotals[col.key];
                    if (idx === 0 && total === undefined) {
                      return (
                        <td key={col.key} className="px-4 py-3 text-xs text-muted-foreground">
                          {processedData.length} รายการ
                        </td>
                      );
                    }
                    if (total !== undefined) {
                      return (
                        <td key={col.key} className="px-4 py-3 text-right font-mono text-primary">
                          {col.isCurrency
                            ? total.toLocaleString("th-TH", { minimumFractionDigits: 2 })
                            : total.toLocaleString("th-TH")}
                        </td>
                      );
                    }
                    return <td key={col.key}></td>;
                  })}
                </tr>
              </tfoot>
            )}
          </table>
        </div>
      </Card>
    </div>
  );
}
