// Generator script for Thai Standard Chart of Accounts (ผังบัญชีมาตรฐานไทย 3 ระดับ)
// Follows Thai TFRS for NPAEs, DBD standards, Revenue Code (กรมสรรพากร)
// Generates:
// 1. docs/examples/thai-chart-of-accounts-standard.json
// 2. seed_thai_chart_of_accounts.sql

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, '..');

const accounts = [
  // ==========================================================================
  // หมวด 1: สินทรัพย์ (Assets)
  // ==========================================================================
  // [Level 1]
  {
    accountcode: '1000',
    nameTh: 'สินทรัพย์',
    nameEn: 'Assets',
    accounttype: 'asset',
    parentaccountcode: '',
    normalbalance: 'debit',
    allowposting: false,
    level: 1,
    iscash: false,
    accountgroup: 'BM69-A',
  },

  // [Level 2]
  {
    accountcode: '1100',
    nameTh: 'สินทรัพย์หมุนเวียน',
    nameEn: 'Current Assets',
    accounttype: 'asset',
    parentaccountcode: '1000',
    normalbalance: 'debit',
    allowposting: false,
    level: 2,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1200',
    nameTh: 'สินทรัพย์ไม่หมุนเวียน',
    nameEn: 'Non-Current Assets',
    accounttype: 'asset',
    parentaccountcode: '1000',
    normalbalance: 'debit',
    allowposting: false,
    level: 2,
    iscash: false,
    accountgroup: 'BM69-A',
  },

  // [Level 3] ภายใต้ 1100 (สินทรัพย์หมุนเวียน)
  {
    accountcode: '1111',
    nameTh: 'เงินสดในมือ',
    nameEn: 'Cash on Hand',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: true,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1112',
    nameTh: 'เงินสดย่อย - สำนักงานใหญ่',
    nameEn: 'Petty Cash - Head Office',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: true,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1113',
    nameTh: 'เงินสดย่อย - ฝ่ายปฏิบัติการและสาขา',
    nameEn: 'Petty Cash - Operations & Branch',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: true,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1121',
    nameTh: 'เงินฝากกระแสรายวัน - ธนาคารกสิกรไทย',
    nameEn: 'Cash at Bank - Current KBANK',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: true,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1122',
    nameTh: 'เงินฝากกระแสรายวัน - ธนาคารกรุงเทพ',
    nameEn: 'Cash at Bank - Current BBL',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: true,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1123',
    nameTh: 'เงินฝากกระแสรายวัน - ธนาคารไทยพาณิชย์',
    nameEn: 'Cash at Bank - Current SCB',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: true,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1124',
    nameTh: 'เงินฝากออมทรัพย์ - ธนาคารกสิกรไทย',
    nameEn: 'Cash at Bank - Savings KBANK',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: true,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1125',
    nameTh: 'เงินฝากออมทรัพย์ - ธนาคารกรุงเทพ',
    nameEn: 'Cash at Bank - Savings BBL',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: true,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1126',
    nameTh: 'เงินฝากออมทรัพย์ - ธนาคารไทยพาณิชย์',
    nameEn: 'Cash at Bank - Savings SCB',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: true,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1127',
    nameTh: 'เงินฝากประจำระยะสั้น (ไม่เกิน 3 เดือน)',
    nameEn: 'Short-term Fixed Deposit',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: true,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1131',
    nameTh: 'ลูกหนี้การค้า - ในประเทศ',
    nameEn: 'Trade Accounts Receivable - Domestic',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1132',
    nameTh: 'ลูกหนี้การค้า - ต่างประเทศ',
    nameEn: 'Trade Accounts Receivable - Overseas',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1133',
    nameTh: 'ตั๋วเงินรับการค้า',
    nameEn: 'Notes Receivable',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1134',
    nameTh: 'เช็ครับลงวันที่ล่วงหน้า',
    nameEn: 'Post-dated Cheques Receivable',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1138',
    nameTh: 'ลูกหนี้อื่นและเงินยืมทดรอง',
    nameEn: 'Other Receivables & Advances',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1139',
    nameTh: 'ค่าเผื่อผลขาดทุนด้านเครดิตที่คาดว่าจะเกิดขึ้น',
    nameEn: 'Allowance for Expected Credit Losses',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1141',
    nameTh: 'สินค้าสำเร็จรูป',
    nameEn: 'Finished Goods',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1142',
    nameTh: 'สินค้าระหว่างทำ / งานระหว่างทำ',
    nameEn: 'Work in Process',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1143',
    nameTh: 'วัตถุดิบและส่วนประกอบ',
    nameEn: 'Raw Materials & Components',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1144',
    nameTh: 'วัสดุสิ้นเปลืองและบรรจุภัณฑ์',
    nameEn: 'Factory Supplies & Packaging',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1145',
    nameTh: 'สินค้าระหว่างทาง',
    nameEn: 'Goods in Transit',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1149',
    nameTh: 'ค่าเผื่อการลดมูลค่าสินค้าคงเหลือ',
    nameEn: 'Allowance for Inventory Devaluation',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1151',
    nameTh: 'ภาษีซื้อ',
    nameEn: 'Input VAT',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1152',
    nameTh: 'ภาษีซื้อยังไม่ถึงกำหนดชำระ',
    nameEn: 'Undue Input VAT',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1153',
    nameTh: 'ภาษีเงินได้ถูกหัก ณ ที่จ่าย (WHT ถูกหัก)',
    nameEn: 'Withholding Tax Receivable',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1154',
    nameTh: 'ภาษีเงินได้นิติบุคคลจ่ายล่วงหน้า (ภ.ง.ด.51)',
    nameEn: 'Prepaid Corporate Income Tax',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1161',
    nameTh: 'ค่าเบี้ยประกันภัยจ่ายล่วงหน้า',
    nameEn: 'Prepaid Insurance',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1162',
    nameTh: 'ค่าเช่าจ่ายล่วงหน้า',
    nameEn: 'Prepaid Rent',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1163',
    nameTh: 'เงินมัดจำค่าสินค้าและบริการล่วงหน้า',
    nameEn: 'Advance Payments for Goods & Services',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1169',
    nameTh: 'สินทรัพย์หมุนเวียนอื่น',
    nameEn: 'Other Current Assets',
    accounttype: 'asset',
    parentaccountcode: '1100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },

  // [Level 3] ภายใต้ 1200 (สินทรัพย์ไม่หมุนเวียน)
  {
    accountcode: '1211',
    nameTh: 'ที่ดิน',
    nameEn: 'Land',
    accounttype: 'asset',
    parentaccountcode: '1200',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1212',
    nameTh: 'ส่วนปรับปรุงที่ดิน',
    nameEn: 'Land Improvements',
    accounttype: 'asset',
    parentaccountcode: '1200',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1213',
    nameTh: 'อาคารและสิ่งปลูกสร้าง',
    nameEn: 'Buildings & Constructions',
    accounttype: 'asset',
    parentaccountcode: '1200',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1214',
    nameTh: 'ส่วนปรับปรุงอาคารและระบบสาธารณูปโภค',
    nameEn: 'Building Improvements & Systems',
    accounttype: 'asset',
    parentaccountcode: '1200',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1221',
    nameTh: 'เครื่องจักรและอุปกรณ์โรงงาน',
    nameEn: 'Machinery & Factory Equipment',
    accounttype: 'asset',
    parentaccountcode: '1200',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1222',
    nameTh: 'เครื่องตกแต่ง ติดตั้ง และเฟอร์นิเจอร์',
    nameEn: 'Furniture & Fixtures',
    accounttype: 'asset',
    parentaccountcode: '1200',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1223',
    nameTh: 'เครื่องใช้และอุปกรณ์สำนักงาน',
    nameEn: 'Office Equipment',
    accounttype: 'asset',
    parentaccountcode: '1200',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1224',
    nameTh: 'คอมพิวเตอร์และอุปกรณ์ประมวลผล',
    nameEn: 'Computer & Hardware Equipment',
    accounttype: 'asset',
    parentaccountcode: '1200',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1231',
    nameTh: 'ยานพาหนะและรถบรรทุกขนส่ง',
    nameEn: 'Vehicles & Transport Trucks',
    accounttype: 'asset',
    parentaccountcode: '1200',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1241',
    nameTh: 'งานระหว่างก่อสร้างและติดตั้งเครื่องจักร',
    nameEn: 'Construction & Installation in Progress',
    accounttype: 'asset',
    parentaccountcode: '1200',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1281',
    nameTh: 'ค่าเสื่อมราคาสะสม - ส่วนปรับปรุงที่ดิน',
    nameEn: 'Acc. Dep. - Land Improvements',
    accounttype: 'asset',
    parentaccountcode: '1200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1282',
    nameTh: 'ค่าเสื่อมราคาสะสม - อาคารและสิ่งปลูกสร้าง',
    nameEn: 'Acc. Dep. - Buildings',
    accounttype: 'asset',
    parentaccountcode: '1200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1283',
    nameTh: 'ค่าเสื่อมราคาสะสม - ส่วนปรับปรุงอาคาร',
    nameEn: 'Acc. Dep. - Building Improvements',
    accounttype: 'asset',
    parentaccountcode: '1200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1284',
    nameTh: 'ค่าเสื่อมราคาสะสม - เครื่องจักรและอุปกรณ์',
    nameEn: 'Acc. Dep. - Machinery & Equipment',
    accounttype: 'asset',
    parentaccountcode: '1200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1285',
    nameTh: 'ค่าเสื่อมราคาสะสม - เครื่องตกแต่งและติดตั้ง',
    nameEn: 'Acc. Dep. - Furniture & Fixtures',
    accounttype: 'asset',
    parentaccountcode: '1200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1286',
    nameTh: 'ค่าเสื่อมราคาสะสม - เครื่องใช้สำนักงาน',
    nameEn: 'Acc. Dep. - Office Equipment',
    accounttype: 'asset',
    parentaccountcode: '1200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1287',
    nameTh: 'ค่าเสื่อมราคาสะสม - คอมพิวเตอร์และอุปกรณ์',
    nameEn: 'Acc. Dep. - Computer & Hardware',
    accounttype: 'asset',
    parentaccountcode: '1200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1288',
    nameTh: 'ค่าเสื่อมราคาสะสม - ยานพาหนะ',
    nameEn: 'Acc. Dep. - Vehicles',
    accounttype: 'asset',
    parentaccountcode: '1200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1291',
    nameTh: 'โปรแกรมคอมพิวเตอร์และสิทธิการใช้งาน',
    nameEn: 'Software & Licenses',
    accounttype: 'asset',
    parentaccountcode: '1200',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1292',
    nameTh: 'ค่าตัดจำหน่ายสะสม - โปรแกรมคอมพิวเตอร์',
    nameEn: 'Acc. Amortization - Software',
    accounttype: 'asset',
    parentaccountcode: '1200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },
  {
    accountcode: '1295',
    nameTh: 'เงินประกันและเงินมัดจำระยะยาว',
    nameEn: 'Long-term Deposits & Guarantees',
    accounttype: 'asset',
    parentaccountcode: '1200',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-A',
  },

  // ==========================================================================
  // หมวด 2: หนี้สิน (Liabilities)
  // ==========================================================================
  // [Level 1]
  {
    accountcode: '2000',
    nameTh: 'หนี้สิน',
    nameEn: 'Liabilities',
    accounttype: 'liability',
    parentaccountcode: '',
    normalbalance: 'credit',
    allowposting: false,
    level: 1,
    iscash: false,
    accountgroup: 'BM69-L',
  },

  // [Level 2]
  {
    accountcode: '2100',
    nameTh: 'หนี้สินหมุนเวียน',
    nameEn: 'Current Liabilities',
    accounttype: 'liability',
    parentaccountcode: '2000',
    normalbalance: 'credit',
    allowposting: false,
    level: 2,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2200',
    nameTh: 'หนี้สินไม่หมุนเวียน',
    nameEn: 'Non-Current Liabilities',
    accounttype: 'liability',
    parentaccountcode: '2000',
    normalbalance: 'credit',
    allowposting: false,
    level: 2,
    iscash: false,
    accountgroup: 'BM69-L',
  },

  // [Level 3] ภายใต้ 2100 (หนี้สินหมุนเวียน)
  {
    accountcode: '2111',
    nameTh: 'เจ้าหนี้การค้า - ในประเทศ',
    nameEn: 'Trade Accounts Payable - Domestic',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2112',
    nameTh: 'เจ้าหนี้การค้า - ต่างประเทศ',
    nameEn: 'Trade Accounts Payable - Overseas',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2113',
    nameTh: 'ตั๋วเงินจ่ายการค้า',
    nameEn: 'Notes Payable',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2114',
    nameTh: 'เช็คจ่ายลงวันที่ล่วงหน้า',
    nameEn: 'Post-dated Cheques Payable',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2121',
    nameTh: 'เจ้าหนี้อื่นและเงินทดรองรับ',
    nameEn: 'Other Payables & Advances',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2122',
    nameTh: 'เจ้าหนี้กรมสรรพากร',
    nameEn: 'Revenue Department Payable',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2131',
    nameTh: 'ภาษีขาย',
    nameEn: 'Output VAT',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2132',
    nameTh: 'ภาษีขายยังไม่ถึงกำหนดชำระ',
    nameEn: 'Undue Output VAT',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2141',
    nameTh: 'ภาษีเงินได้หัก ณ ที่จ่ายค้างจ่าย - ภ.ง.ด.1 (เงินเดือน)',
    nameEn: 'WHT Payable - P.N.D.1 (Salaries)',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2142',
    nameTh: 'ภาษีเงินได้หัก ณ ที่จ่ายค้างจ่าย - ภ.ง.ด.3 (บุคคลธรรมดา)',
    nameEn: 'WHT Payable - P.N.D.3 (Individuals)',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2143',
    nameTh: 'ภาษีเงินได้หัก ณ ที่จ่ายค้างจ่าย - ภ.ง.ด.53 (นิติบุคคล)',
    nameEn: 'WHT Payable - P.N.D.53 (Corporations)',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2144',
    nameTh: 'ภาษีเงินได้หัก ณ ที่จ่ายค้างจ่าย - ภ.ง.ด.2 (ดอกเบี้ย/ปันผล)',
    nameEn: 'WHT Payable - P.N.D.2',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2145',
    nameTh: 'ภาษีเงินได้หัก ณ ที่จ่ายค้างจ่าย - ภ.ง.ด.54 (ส่งไปต่างประเทศ)',
    nameEn: 'WHT Payable - P.N.D.54 (Overseas)',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2151',
    nameTh: 'เงินสมทบกองทุนประกันสังคมค้างจ่าย (ลูกจ้าง+นายจ้าง)',
    nameEn: 'Social Security Fund Payable',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2152',
    nameTh: 'เงินเดือนและค่าจ้างค้างจ่าย',
    nameEn: 'Accrued Salaries & Wages',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2153',
    nameTh: 'ค่าเช่าค้างจ่าย',
    nameEn: 'Accrued Rent Expenses',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2154',
    nameTh: 'ค่าน้ำประปาและค่าไฟฟ้าค้างจ่าย',
    nameEn: 'Accrued Utilities Expenses',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2155',
    nameTh: 'ค่าโทรศัพท์และอินเทอร์เน็ตค้างจ่าย',
    nameEn: 'Accrued Telephone & Internet',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2156',
    nameTh: 'ค่าสอบบัญชีและทำบัญชีค้างจ่าย',
    nameEn: 'Accrued Audit & Accounting Fees',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2157',
    nameTh: 'ดอกเบี้ยค้างจ่าย',
    nameEn: 'Accrued Interest Expenses',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2158',
    nameTh: 'โบนัสพนักงานค้างจ่าย',
    nameEn: 'Accrued Staff Bonuses',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2159',
    nameTh: 'ค่าใช้จ่ายค้างจ่ายอื่น',
    nameEn: 'Other Accrued Expenses',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2161',
    nameTh: 'เงินรับล่วงหน้าค่าสินค้าและบริการจากลูกค้า',
    nameEn: 'Advances Received from Customers',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2171',
    nameTh: 'เงินเบิกเกินบัญชีธนาคาร (O/D)',
    nameEn: 'Bank Overdrafts (O/D)',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2172',
    nameTh: 'เงินกู้ยืมระยะสั้นจากสถาบันการเงิน',
    nameEn: 'Short-term Borrowings from Banks',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2173',
    nameTh: 'เงินกู้ยืมระยะสั้นจากกรรมการหรือบุคคลที่เกี่ยวข้องกัน',
    nameEn: 'Short-term Loans from Directors',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2181',
    nameTh: 'ส่วนของหนี้สินระยะยาวที่ถึงกำหนดชำระภายในหนึ่งปี',
    nameEn: 'Current Portion of Long-term Debt',
    accounttype: 'liability',
    parentaccountcode: '2100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },

  // [Level 3] ภายใต้ 2200 (หนี้สินไม่หมุนเวียน)
  {
    accountcode: '2211',
    nameTh: 'เงินกู้ยืมระยะยาวจากสถาบันการเงิน',
    nameEn: 'Long-term Bank Loans',
    accounttype: 'liability',
    parentaccountcode: '2200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2212',
    nameTh: 'หนี้สินตามสัญญาเช่าทางการเงินระยะยาว',
    nameEn: 'Long-term Financial Lease Liabilities',
    accounttype: 'liability',
    parentaccountcode: '2200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2221',
    nameTh: 'เงินกู้ยืมระยะยาวจากกรรมการหรือผู้ถือหุ้น',
    nameEn: 'Long-term Loans from Directors/Shareholders',
    accounttype: 'liability',
    parentaccountcode: '2200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2231',
    nameTh: 'ประมาณการหนี้สินผลประโยชน์พนักงาน',
    nameEn: 'Provision for Employee Benefits',
    accounttype: 'liability',
    parentaccountcode: '2200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },
  {
    accountcode: '2291',
    nameTh: 'หนี้สินไม่หมุนเวียนอื่น',
    nameEn: 'Other Non-Current Liabilities',
    accounttype: 'liability',
    parentaccountcode: '2200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-L',
  },

  // ==========================================================================
  // หมวด 3: ส่วนของเจ้าของ (Equity)
  // ==========================================================================
  // [Level 1]
  {
    accountcode: '3000',
    nameTh: 'ส่วนของเจ้าของ',
    nameEn: 'Equity',
    accounttype: 'equity',
    parentaccountcode: '',
    normalbalance: 'credit',
    allowposting: false,
    level: 1,
    iscash: false,
    accountgroup: 'BM69-E',
  },

  // [Level 2]
  {
    accountcode: '3100',
    nameTh: 'ทุนจดทะเบียนและส่วนเกินทุน',
    nameEn: 'Share Capital & Premium',
    accounttype: 'equity',
    parentaccountcode: '3000',
    normalbalance: 'credit',
    allowposting: false,
    level: 2,
    iscash: false,
    accountgroup: 'BM69-E',
  },
  {
    accountcode: '3200',
    nameTh: 'กำไร (ขาดทุน) สะสม',
    nameEn: 'Retained Earnings',
    accounttype: 'equity',
    parentaccountcode: '3000',
    normalbalance: 'credit',
    allowposting: false,
    level: 2,
    iscash: false,
    accountgroup: 'BM69-E',
  },

  // [Level 3] ภายใต้ 3100
  {
    accountcode: '3111',
    nameTh: 'ทุนเรือนหุ้น - หุ้นสามัญ',
    nameEn: 'Authorized Share Capital - Common Shares',
    accounttype: 'equity',
    parentaccountcode: '3100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-E',
  },
  {
    accountcode: '3112',
    nameTh: 'ทุนเรือนหุ้น - หุ้นบุริมสิทธิ',
    nameEn: 'Authorized Share Capital - Preferred Shares',
    accounttype: 'equity',
    parentaccountcode: '3100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-E',
  },
  {
    accountcode: '3121',
    nameTh: 'ส่วนเกินมูลค่าหุ้นสามัญ',
    nameEn: 'Share Premium - Common Shares',
    accounttype: 'equity',
    parentaccountcode: '3100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-E',
  },
  {
    accountcode: '3131',
    nameTh: 'ทุนส่วนของเจ้าของ (ห้างหุ้นส่วน/บุคคลธรรมดา)',
    nameEn: "Owner's / Partner's Capital",
    accounttype: 'equity',
    parentaccountcode: '3100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-E',
  },
  {
    accountcode: '3132',
    nameTh: 'เงินถอนใช้ส่วนตัวของเจ้าของกิจการ',
    nameEn: "Owner's Drawings",
    accounttype: 'equity',
    parentaccountcode: '3100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-E',
  },

  // [Level 3] ภายใต้ 3200
  {
    accountcode: '3211',
    nameTh: 'สำรองตามกฎหมาย',
    nameEn: 'Legal Reserve',
    accounttype: 'equity',
    parentaccountcode: '3200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-E',
  },
  {
    accountcode: '3212',
    nameTh: 'สำรองอื่นเพื่อวัตถุประสงค์เฉพาะ',
    nameEn: 'Other Appropriated Reserves',
    accounttype: 'equity',
    parentaccountcode: '3200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-E',
  },
  {
    accountcode: '3221',
    nameTh: 'กำไร (ขาดทุน) สะสมยังไม่ได้จัดสรร',
    nameEn: 'Unappropriated Retained Earnings',
    accounttype: 'equity',
    parentaccountcode: '3200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-E',
  },
  {
    accountcode: '3222',
    nameTh: 'กำไร (ขาดทุน) สุทธิประจำปี',
    nameEn: 'Net Profit/Loss for Current Year',
    accounttype: 'equity',
    parentaccountcode: '3200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-E',
  },
  {
    accountcode: '3223',
    nameTh: 'เงินปันผลจ่าย',
    nameEn: 'Dividends Declared & Paid',
    accounttype: 'equity',
    parentaccountcode: '3200',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-E',
  },

  // ==========================================================================
  // หมวด 4: รายได้ (Revenue)
  // ==========================================================================
  // [Level 1]
  {
    accountcode: '4000',
    nameTh: 'รายได้',
    nameEn: 'Income',
    accounttype: 'income',
    parentaccountcode: '',
    normalbalance: 'credit',
    allowposting: false,
    level: 1,
    iscash: false,
    accountgroup: 'BM69-R',
  },

  // [Level 2]
  {
    accountcode: '4100',
    nameTh: 'รายได้จากการขายและการให้บริการ',
    nameEn: 'Revenue from Sales & Services',
    accounttype: 'income',
    parentaccountcode: '4000',
    normalbalance: 'credit',
    allowposting: false,
    level: 2,
    iscash: false,
    accountgroup: 'BM69-R',
  },
  {
    accountcode: '4200',
    nameTh: 'รายได้อื่น',
    nameEn: 'Other Income',
    accounttype: 'income',
    parentaccountcode: '4000',
    normalbalance: 'credit',
    allowposting: false,
    level: 2,
    iscash: false,
    accountgroup: 'BM69-R',
  },

  // [Level 3] ภายใต้ 4100
  {
    accountcode: '4111',
    nameTh: 'รายได้จากการขายสินค้า - มีภาษีมูลค่าเพิ่ม 7%',
    nameEn: 'Sales Revenue - VAT 7%',
    accounttype: 'income',
    parentaccountcode: '4100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-R',
  },
  {
    accountcode: '4112',
    nameTh: 'รายได้จากการขายสินค้า - อัตราภาษี 0% / ส่งออก',
    nameEn: 'Sales Revenue - Zero Rated / Export',
    accounttype: 'income',
    parentaccountcode: '4100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-R',
  },
  {
    accountcode: '4113',
    nameTh: 'รายได้จากการขายสินค้า - ได้รับยกเว้นภาษีมูลค่าเพิ่ม',
    nameEn: 'Sales Revenue - VAT Exempted',
    accounttype: 'income',
    parentaccountcode: '4100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-R',
  },
  {
    accountcode: '4121',
    nameTh: 'รายได้จากการให้บริการ - มีภาษีมูลค่าเพิ่ม 7%',
    nameEn: 'Service Income - VAT 7%',
    accounttype: 'income',
    parentaccountcode: '4100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-R',
  },
  {
    accountcode: '4122',
    nameTh: 'รายได้จากการให้บริการ - ได้รับยกเว้นภาษีมูลค่าเพิ่ม',
    nameEn: 'Service Income - VAT Exempted',
    accounttype: 'income',
    parentaccountcode: '4100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-R',
  },
  {
    accountcode: '4131',
    nameTh: 'รับคืนสินค้าและลดหนี้ขาย',
    nameEn: 'Sales Returns and Allowances',
    accounttype: 'income',
    parentaccountcode: '4100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-R',
  },
  {
    accountcode: '4132',
    nameTh: 'ส่วนลดจ่าย',
    nameEn: 'Sales Cash Discounts',
    accounttype: 'income',
    parentaccountcode: '4100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-R',
  },
  {
    accountcode: '4141',
    nameTh: 'รายได้ค่าบริการขนส่งและจัดส่งสินค้า',
    nameEn: 'Freight & Delivery Income',
    accounttype: 'income',
    parentaccountcode: '4100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-R',
  },

  // [Level 3] ภายใต้ 4200
  {
    accountcode: '4211',
    nameTh: 'ดอกเบี้ยรับจากสถาบันการเงิน',
    nameEn: 'Interest Income from Banks',
    accounttype: 'income',
    parentaccountcode: '4200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-R',
  },
  {
    accountcode: '4212',
    nameTh: 'เงินปันผลรับจากเงินลงทุน',
    nameEn: 'Dividend Income',
    accounttype: 'income',
    parentaccountcode: '4200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-R',
  },
  {
    accountcode: '4221',
    nameTh: 'กำไรจากการจำหน่ายทรัพย์สินถาวร',
    nameEn: 'Gain on Disposal of Fixed Assets',
    accounttype: 'income',
    parentaccountcode: '4200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-R',
  },
  {
    accountcode: '4231',
    nameTh: 'กำไรจากอัตราแลกเปลี่ยนเงินตราต่างประเทศ',
    nameEn: 'Gain on Foreign Exchange',
    accounttype: 'income',
    parentaccountcode: '4200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-R',
  },
  {
    accountcode: '4241',
    nameTh: 'รายได้ค่าเช่าอาคารและอุปกรณ์',
    nameEn: 'Rental Income',
    accounttype: 'income',
    parentaccountcode: '4200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-R',
  },
  {
    accountcode: '4251',
    nameTh: 'หนี้สูญได้รับคืน',
    nameEn: 'Bad Debts Recovered',
    accounttype: 'income',
    parentaccountcode: '4200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-R',
  },
  {
    accountcode: '4291',
    nameTh: 'รายได้เบ็ดเตล็ดอื่น',
    nameEn: 'Miscellaneous Income',
    accounttype: 'income',
    parentaccountcode: '4200',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-R',
  },

  // ==========================================================================
  // หมวด 5: ค่าใช้จ่าย (Expenses)
  // ==========================================================================
  // [Level 1]
  {
    accountcode: '5000',
    nameTh: 'ค่าใช้จ่าย',
    nameEn: 'Expenses',
    accounttype: 'expense',
    parentaccountcode: '',
    normalbalance: 'debit',
    allowposting: false,
    level: 1,
    iscash: false,
    accountgroup: 'BM69-X',
  },

  // [Level 2]
  {
    accountcode: '5100',
    nameTh: 'ต้นทุนขายและบริการ',
    nameEn: 'Cost of Goods Sold & Services',
    accounttype: 'expense',
    parentaccountcode: '5000',
    normalbalance: 'debit',
    allowposting: false,
    level: 2,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5200',
    nameTh: 'ค่าใช้จ่ายในการขาย',
    nameEn: 'Selling Expenses',
    accounttype: 'expense',
    parentaccountcode: '5000',
    normalbalance: 'debit',
    allowposting: false,
    level: 2,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5300',
    nameTh: 'ค่าใช้จ่ายในการบริหาร',
    nameEn: 'Administrative Expenses',
    accounttype: 'expense',
    parentaccountcode: '5000',
    normalbalance: 'debit',
    allowposting: false,
    level: 2,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5400',
    nameTh: 'ต้นทุนทางการเงินและภาษีเงินได้',
    nameEn: 'Financial Costs & Income Tax',
    accounttype: 'expense',
    parentaccountcode: '5000',
    normalbalance: 'debit',
    allowposting: false,
    level: 2,
    iscash: false,
    accountgroup: 'BM69-X',
  },

  // [Level 3] ภายใต้ 5100 (ต้นทุนขายและบริการ)
  {
    accountcode: '5111',
    nameTh: 'ซื้อสินค้าสำเร็จรูป',
    nameEn: 'Purchases of Merchandise',
    accounttype: 'expense',
    parentaccountcode: '5100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5112',
    nameTh: 'ค่าขนส่งเข้า',
    nameEn: 'Freight-In',
    accounttype: 'expense',
    parentaccountcode: '5100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5113',
    nameTh: 'ส่งคืนสินค้าและส่วนลดที่ได้รับ',
    nameEn: 'Purchase Returns and Allowances',
    accounttype: 'expense',
    parentaccountcode: '5100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5114',
    nameTh: 'ส่วนลดรับ',
    nameEn: 'Purchase Cash Discounts',
    accounttype: 'expense',
    parentaccountcode: '5100',
    normalbalance: 'credit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5121',
    nameTh: 'ต้นทุนสินค้าสำเร็จรูปที่ขาย',
    nameEn: 'Cost of Goods Sold',
    accounttype: 'expense',
    parentaccountcode: '5100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5131',
    nameTh: 'ต้นทุนค่าแรงและบริการ',
    nameEn: 'Direct Labor & Service Costs',
    accounttype: 'expense',
    parentaccountcode: '5100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5132',
    nameTh: 'ค่าจ้างเหมาบริการช่วงภายนอก (Subcontractor)',
    nameEn: 'Subcontractor Costs',
    accounttype: 'expense',
    parentaccountcode: '5100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5141',
    nameTh: 'สินค้าสูญหาย เสียหาย และสินค้าชำรุด',
    nameEn: 'Inventory Shrinkage & Damage',
    accounttype: 'expense',
    parentaccountcode: '5100',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },

  // [Level 3] ภายใต้ 5200 (ค่าใช้จ่ายในการขาย)
  {
    accountcode: '5211',
    nameTh: 'เงินเดือน ค่าล่วงเวลา และเบี้ยเลี้ยงฝ่ายขาย',
    nameEn: 'Sales Salaries, Overtime & Allowances',
    accounttype: 'expense',
    parentaccountcode: '5200',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5212',
    nameTh: 'ค่านายหน้าและค่าคอมมิชชั่นฝ่ายขาย',
    nameEn: 'Sales Commissions & Incentives',
    accounttype: 'expense',
    parentaccountcode: '5200',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5221',
    nameTh: 'ค่าโฆษณา ประชาสัมพันธ์ และการตลาดออนไลน์',
    nameEn: 'Advertising, PR & Online Marketing',
    accounttype: 'expense',
    parentaccountcode: '5200',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5222',
    nameTh: 'ค่าส่งเสริมการขาย ของแถม และตัวอย่างสินค้า',
    nameEn: 'Sales Promotion, Gifts & Samples',
    accounttype: 'expense',
    parentaccountcode: '5200',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5231',
    nameTh: 'ค่าขนส่งสินค้าออกและบริการจัดส่งให้ลูกค้า',
    nameEn: 'Outward Freight & Shipping to Customers',
    accounttype: 'expense',
    parentaccountcode: '5200',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5232',
    nameTh: 'ค่าวัสดุหีบห่อและบรรจุภัณฑ์สำหรับการขาย',
    nameEn: 'Packaging & Packing Materials',
    accounttype: 'expense',
    parentaccountcode: '5200',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5241',
    nameTh: 'ค่าจัดงานแสดงสินค้าและการออกบูธ',
    nameEn: 'Exhibition & Trade Fair Expenses',
    accounttype: 'expense',
    parentaccountcode: '5200',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5251',
    nameTh: 'ค่าน้ำมันและค่าเดินทางพบลูกค้าฝ่ายขาย',
    nameEn: 'Sales Fuel & Travel Expenses',
    accounttype: 'expense',
    parentaccountcode: '5200',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5291',
    nameTh: 'ค่าใช้จ่ายในการขายอื่น',
    nameEn: 'Other Selling Expenses',
    accounttype: 'expense',
    parentaccountcode: '5200',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },

  // [Level 3] ภายใต้ 5300 (ค่าใช้จ่ายในการบริหาร)
  {
    accountcode: '5311',
    nameTh: 'เงินเดือน ค่าจ้าง และค่าล่วงเวลาพนักงานสำนักงาน',
    nameEn: 'Office Salaries, Wages & Overtime',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5312',
    nameTh: 'ค่าตอบแทนและเบี้ยประชุมกรรมการ',
    nameEn: "Directors' Remuneration & Meeting Fees",
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5313',
    nameTh: 'โบนัสพนักงานประจำปี',
    nameEn: 'Annual Staff Bonuses',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5314',
    nameTh: 'เงินสมทบกองทุนประกันสังคม (ส่วนของนายจ้าง)',
    nameEn: "Social Security Fund - Employer's Contribution",
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5315',
    nameTh: 'เงินสมทบกองทุนเงินทดแทนและกองทุนสำรองเลี้ยงชีพ',
    nameEn: 'Workmen Compensation & Provident Fund',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5316',
    nameTh: 'ค่าสวัสดิการพนักงานและชุดยูนิฟอร์ม',
    nameEn: 'Staff Welfare & Uniforms',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5317',
    nameTh: 'ค่าฝึกอบรมและสัมมนาบุคลากร',
    nameEn: 'Training & Seminar Expenses',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5321',
    nameTh: 'ค่าเช่าอาคารสำนักงานและพื้นที่ประกอบการ',
    nameEn: 'Office Building Rent',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5322',
    nameTh: 'ค่าน้ำประปา',
    nameEn: 'Water Utility Expenses',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5323',
    nameTh: 'ค่าไฟฟ้า',
    nameEn: 'Electricity Utility Expenses',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5324',
    nameTh: 'ค่าโทรศัพท์และค่าบริการโทรคมนาคม',
    nameEn: 'Telephone & Telecom Expenses',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5325',
    nameTh: 'ค่าบริการอินเทอร์เน็ต ระบบเซิร์ฟเวอร์ และคลาวด์',
    nameEn: 'Internet, Server & Cloud Hosting Services',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5331',
    nameTh: 'ค่าเครื่องเขียน แบบพิมพ์ และวัสดุสำนักงาน',
    nameEn: 'Stationery, Printing & Office Supplies',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5332',
    nameTh: 'ค่าไปรษณีย์และค่าส่งเอกสารพัสดุ',
    nameEn: 'Postal & Courier Expenses',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5341',
    nameTh: 'ค่าตรวจสอบบัญชี (Audit Fees)',
    nameEn: 'Audit Fees',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5342',
    nameTh: 'ค่าจัดทำบัญชีและที่ปรึกษาภาษีอากร',
    nameEn: 'Accounting & Tax Consultation Fees',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5343',
    nameTh: 'ค่าธรรมเนียมวิชาชีพกฎหมายและที่ปรึกษาธุรกิจ',
    nameEn: 'Legal & Business Advisory Fees',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5351',
    nameTh: 'ค่าเบี้ยประกันภัยทรัพย์สิน อาคาร และยานพาหนะ',
    nameEn: 'Property, Building & Vehicle Insurance',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5352',
    nameTh: 'ค่าซ่อมแซมและบำรุงรักษาอาคารและอุปกรณ์',
    nameEn: 'Repairs & Maintenance Expenses',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5353',
    nameTh: 'ค่าบริการทำความสะอาดและรักษาความปลอดภัย',
    nameEn: 'Cleaning & Security Services',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5361',
    nameTh: 'ค่าเสื่อมราคา - ส่วนปรับปรุงที่ดิน',
    nameEn: 'Depreciation - Land Improvements',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5362',
    nameTh: 'ค่าเสื่อมราคา - อาคารและสิ่งปลูกสร้าง',
    nameEn: 'Depreciation - Buildings',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5363',
    nameTh: 'ค่าเสื่อมราคา - ส่วนปรับปรุงอาคาร',
    nameEn: 'Depreciation - Building Improvements',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5364',
    nameTh: 'ค่าเสื่อมราคา - เครื่องจักรและอุปกรณ์',
    nameEn: 'Depreciation - Machinery & Equipment',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5365',
    nameTh: 'ค่าเสื่อมราคา - เครื่องตกแต่งและติดตั้ง',
    nameEn: 'Depreciation - Furniture & Fixtures',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5366',
    nameTh: 'ค่าเสื่อมราคา - เครื่องใช้สำนักงาน',
    nameEn: 'Depreciation - Office Equipment',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5367',
    nameTh: 'ค่าเสื่อมราคา - คอมพิวเตอร์และอุปกรณ์',
    nameEn: 'Depreciation - Computer & Hardware',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5368',
    nameTh: 'ค่าเสื่อมราคา - ยานพาหนะ',
    nameEn: 'Depreciation - Vehicles',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5371',
    nameTh: 'ค่าตัดจำหน่ายโปรแกรมคอมพิวเตอร์และซอฟต์แวร์',
    nameEn: 'Amortization - Software & Applications',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5381',
    nameTh: 'ค่าธรรมเนียมราชการและใบอนุญาตประกอบกิจการ',
    nameEn: 'Government Licenses & Registration Fees',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5382',
    nameTh: 'ภาษีที่ดินและสิ่งปลูกสร้าง',
    nameEn: 'Land and Building Taxes',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5383',
    nameTh: 'ภาษีป้าย',
    nameEn: 'Signboard Tax',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5384',
    nameTh: 'ภาษีซื้อต้องห้าม / ภาษีซื้อที่ไม่สามารถขอคืนได้',
    nameEn: 'Non-refundable Input Tax (Disallowed Input VAT)',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5385',
    nameTh: 'เบี้ยปรับ เงินเพิ่ม และค่าปรับทางภาษีอากร',
    nameEn: 'Tax Penalties, Fines & Surcharges',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5391',
    nameTh: 'ค่ารับรองและบริการลูกค้า',
    nameEn: 'Entertainment & Hospitality Expenses',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5392',
    nameTh: 'เงินบริจาคเพื่อการกุศลและการศึกษา',
    nameEn: 'Charitable & Educational Donations',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5393',
    nameTh: 'หนี้สูญและหนี้สงสัยจะสูญ',
    nameEn: 'Bad Debts & Doubtful Accounts Expense',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5394',
    nameTh: 'ขาดทุนจากอัตราแลกเปลี่ยนเงินตราต่างประเทศ',
    nameEn: 'Loss on Foreign Exchange',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5395',
    nameTh: 'ขาดทุนจากการจำหน่ายและตัดจำหน่ายทรัพย์สิน',
    nameEn: 'Loss on Disposal and Write-off of Assets',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5399',
    nameTh: 'ค่าใช้จ่ายในการบริหารอื่น',
    nameEn: 'Other Administrative Expenses',
    accounttype: 'expense',
    parentaccountcode: '5300',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },

  // [Level 3] ภายใต้ 5400 (ต้นทุนทางการเงินและภาษี)
  {
    accountcode: '5411',
    nameTh: 'ดอกเบี้ยจ่ายเงินกู้ยืมสถาบันการเงิน',
    nameEn: 'Interest Expense - Bank Loans',
    accounttype: 'expense',
    parentaccountcode: '5400',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5412',
    nameTh: 'ดอกเบี้ยจ่ายเงินเบิกเกินบัญชี (O/D)',
    nameEn: 'Interest Expense - Bank Overdraft (O/D)',
    accounttype: 'expense',
    parentaccountcode: '5400',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5413',
    nameTh: 'ดอกเบี้ยจ่ายตามสัญญาเช่าทางการเงิน',
    nameEn: 'Interest Expense - Financial Leases',
    accounttype: 'expense',
    parentaccountcode: '5400',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5421',
    nameTh: 'ค่าธรรมเนียมธนาคารและธุรกรรมทางการเงิน',
    nameEn: 'Bank Charges & Transaction Fees',
    accounttype: 'expense',
    parentaccountcode: '5400',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
  {
    accountcode: '5431',
    nameTh: 'ภาษีเงินได้นิติบุคคลประจำงวด',
    nameEn: 'Corporate Income Tax Expense',
    accounttype: 'expense',
    parentaccountcode: '5400',
    normalbalance: 'debit',
    allowposting: true,
    level: 3,
    iscash: false,
    accountgroup: 'BM69-X',
  },
];

console.log(`Loaded ${accounts.length} total accounts.`);

// Verify Level distribution
const byLevel = { 1: 0, 2: 0, 3: 0, other: 0 };
for (const acc of accounts) {
  byLevel[acc.level] = (byLevel[acc.level] || 0) + 1;
}
console.log('Account distribution by level:', byLevel);

// 1. Sort strictly by accountcode (Rule: การเรียง ให้เรียงตามรหัสบัญชี)
accounts.sort((a, b) => a.accountcode.localeCompare(b.accountcode, undefined, { numeric: true }));

// 2. Ensure parentaccountcode is null if top-level (Rule: ทุกผังบัญชี จะต้องมี field หัวบัญชี ถ้าไม่มีให้เป็น null)
for (const a of accounts) {
  if (!a.parentaccountcode || a.parentaccountcode === '') {
    a.parentaccountcode = null;
  }
}

// 3. Enforce posting rules (Rule: ถ้าผังไหนเป็นหัว มีตัวลูก จะไม่สามารถบันทึกตัวเลขได้, ผังที่บันทึกตัวเลขได้ จะต้องเป็นตัวลูก ไม่มีหางมาต่อ)
const parentCodesSet = new Set(accounts.map((a) => a.parentaccountcode).filter(Boolean));
for (const a of accounts) {
  const hasChildren = parentCodesSet.has(a.accountcode);
  a.allowposting = !hasChildren;
}

// Generate JSON fixture
const jsonFixture = {
  version: '1.0.0',
  description: 'ผังบัญชีตัวอย่างมาตรฐานประเทศไทยสำหรับธุรกิจ SME (TFRS for NPAEs / DBD / สรรพากร)',
  totalAccounts: accounts.length,
  levels: {
    level1: byLevel[1],
    level2: byLevel[2],
    level3: byLevel[3],
  },
  accounts: accounts.map((a) => ({
    accountcode: a.accountcode,
    names: [
      { code: 'th', name: a.nameTh },
      { code: 'en', name: a.nameEn },
    ],
    accounttype: a.accounttype,
    parentaccountcode: a.parentaccountcode,
    normalbalance: a.normalbalance,
    allowposting: a.allowposting,
    isactive: true,
    accountgroup: a.accountgroup,
    iscash: a.iscash,
    level: a.level,
  })),
};

const jsonPath = path.join(root, 'docs/examples/thai-chart-of-accounts-standard.json');
fs.writeFileSync(jsonPath, JSON.stringify(jsonFixture, null, 2), 'utf8');
console.log(`✓ Generated JSON: ${jsonPath}`);

// Generate SQL Script for PostgreSQL
function deterministicId(holding, company, code) {
  const hash = crypto.createHash('md5').update(`${holding}:${company}:${code}`).digest('hex');
  return `${hash.slice(0, 8)}-${hash.slice(8, 12)}-4${hash.slice(13, 16)}-a${hash.slice(17, 20)}-${hash.slice(20, 32)}`;
}

function buildSqlForCompany(holding, company) {
  let sql = `\n-- Accounts for Holding: ${holding}, Company: ${company}\n`;
  for (const a of accounts) {
    const id = deterministicId(holding, company, a.accountcode);
    const payload = JSON.stringify({
      id: id,
      holdingcode: holding,
      businesscode: company,
      version: 1,
      createdat: '2026-09-20T00:00:00.000Z',
      createdby: 'system',
      updatedat: '2026-09-20T00:00:00.000Z',
      updatedby: 'system',
      isdeleted: false,
      accountcode: a.accountcode,
      names: [
        { code: 'th', name: a.nameTh },
        { code: 'en', name: a.nameEn },
      ],
      accounttype: a.accounttype,
      parentaccountcode: a.parentaccountcode,
      normalbalance: a.normalbalance,
      allowposting: a.allowposting,
      isactive: true,
      accountgroup: a.accountgroup,
      iscash: a.iscash,
      level: a.level,
    }).replace(/'/g, "''");

    sql += `INSERT INTO gl_records(company, kind, id, code, version, payload)\n`;
    sql += `VALUES ('${company}', 'accounts', '${id}', '${a.accountcode}', 1, '${payload}'::jsonb)\n`;
    sql += `ON CONFLICT (company, kind, id) DO UPDATE SET\n`;
    sql += `  code = EXCLUDED.code,\n`;
    sql += `  version = gl_records.version + 1,\n`;
    sql += `  payload = EXCLUDED.payload;\n\n`;
  }
  return sql;
}

const groups = [
  { code: 'BM69-A', name: 'สินทรัพย์', kind: 'account-groups' },
  { code: 'BM69-L', name: 'หนี้สิน', kind: 'account-groups' },
  { code: 'BM69-E', name: 'ส่วนของเจ้าของ', kind: 'account-groups' },
  { code: 'BM69-R', name: 'รายได้', kind: 'account-groups' },
  { code: 'BM69-X', name: 'ค่าใช้จ่าย', kind: 'account-groups' },
];

const books = [
  { code: 'JV', name: 'สมุดรายวันทั่วไป' },
  { code: 'PV', name: 'สมุดรายวันจ่าย' },
  { code: 'RV', name: 'สมุดรายวันรับ' },
  { code: 'SV', name: 'สมุดรายวันซื้อ' },
  { code: 'UV', name: 'สมุดรายวันขาย' },
  { code: 'GJ', name: 'สมุดรายวันทั่วไป (GJ)' },
  { code: 'AP', name: 'สมุดรายวันซื้อเชื่อ (AP)' },
  { code: 'AR', name: 'สมุดรายวันขายเชื่อ (AR)' },
];

function generateHoldingSql(holding, companies) {
  let sql = `\n-- ============================================================================\n`;
  sql += `-- Holding: ${holding}\n`;
  sql += `-- ============================================================================\n`;

  for (const cmp of companies) {
    // 1. Fiscal year
    const fyId = deterministicId(holding, cmp, '2569');
    const fyPayload = JSON.stringify({
      id: fyId,
      code: '2569',
      kind: 'fiscal-years',
      startdate: '2026-01-01',
      enddate: '2026-12-31',
      scale: 2,
      profitlossaccount: '3222',
      retainedearningsaccount: '3221',
      closed: false,
      isactive: true,
      version: 1,
      createdat: '2026-09-20T00:00:00.000Z',
      createdby: 'system',
      updatedat: '2026-09-20T00:00:00.000Z',
      updatedby: 'system',
      isdeleted: false,
      holdingcode: holding,
      businesscode: cmp,
    }).replace(/'/g, "''");
    sql += `INSERT INTO gl_records(company, kind, id, code, version, payload)\n`;
    sql += `VALUES ('${cmp}', 'fiscal-years', '${fyId}', '2569', 1, '${fyPayload}'::jsonb)\n`;
    sql += `ON CONFLICT (company, kind, id) DO NOTHING;\n\n`;

    // 2. Journal Books
    for (const b of books) {
      const bId = deterministicId(holding, cmp, b.code);
      const bPayload = JSON.stringify({
        id: bId,
        code: b.code,
        kind: 'journal-books',
        name: b.name,
        isactive: true,
        version: 1,
        createdat: '2026-09-20T00:00:00.000Z',
        createdby: 'system',
        updatedat: '2026-09-20T00:00:00.000Z',
        updatedby: 'system',
        isdeleted: false,
        holdingcode: holding,
        businesscode: cmp,
      }).replace(/'/g, "''");
      sql += `INSERT INTO gl_records(company, kind, id, code, version, payload)\n`;
      sql += `VALUES ('${cmp}', 'journal-books', '${bId}', '${b.code}', 1, '${bPayload}'::jsonb)\n`;
      sql += `ON CONFLICT (company, kind, id) DO NOTHING;\n\n`;
    }

    // 3. Account Groups
    for (const g of groups) {
      const gid = deterministicId(holding, cmp, g.code);
      const gPayload = JSON.stringify({
        id: gid,
        code: g.code,
        kind: 'account-groups',
        name: g.name,
        amount: '0',
        locked: false,
        version: 1,
        isactive: true,
        createdat: '2026-09-20T00:00:00.000Z',
        createdby: 'system',
        isdeleted: false,
        updatedat: '2026-09-20T00:00:00.000Z',
        updatedby: 'system',
        holdingcode: holding,
        businesscode: cmp,
      }).replace(/'/g, "''");

      sql += `INSERT INTO gl_records(company, kind, id, code, version, payload)\n`;
      sql += `VALUES ('${cmp}', 'account-groups', '${gid}', '${g.code}', 1, '${gPayload}'::jsonb)\n`;
      sql += `ON CONFLICT (company, kind, id) DO UPDATE SET payload = EXCLUDED.payload;\n\n`;
    }

    // 4. Accounts
    sql += buildSqlForCompany(holding, cmp);
  }
  return sql;
}

function generateFullSqlForHolding(holding, companies) {
  let fullSql = `-- ============================================================================\n`;
  fullSql += `-- Thai Standard Chart of Accounts for Holding: ${holding} (3 Levels, ${accounts.length} Accounts)\n`;
  fullSql += `-- Compatible with Thai Accounting Standards (TFRS for NPAEs / DBD / RD)\n`;
  fullSql += `-- Wrapped in transaction for ACID safety\n`;
  fullSql += `-- ============================================================================\n\n`;
  fullSql += `BEGIN;\n\n`;
  fullSql += generateHoldingSql(holding, companies);
  fullSql += `COMMIT;\n`;
  return fullSql;
}

const sqlDemoPath = path.join(root, 'seed_thai_chart_of_accounts.sql');
fs.writeFileSync(sqlDemoPath, generateFullSqlForHolding('demo', ['01', 'c01']), 'utf8');
console.log(`✓ Generated SQL: ${sqlDemoPath}`);

const sqlRungruengPath = path.join(root, 'seed_thai_chart_of_accounts_rungrueng.sql');
fs.writeFileSync(sqlRungruengPath, generateFullSqlForHolding('rungrueng', ['01', 'c01']), 'utf8');
console.log(`✓ Generated SQL: ${sqlRungruengPath}`);
