#!/usr/bin/env python3
"""Add missing language keys to languages.json"""
import json
import sys

LANG_FILE = r"D:\bcdev\backend\assets\language\languages.json"

# New keys to add: key -> {th, en}
NEW_KEYS = {
    "account_deletion_step": {"th": "ขั้นตอนที่", "en": "Step"},
    "account_deletion_steps_title": {"th": "ขั้นตอนการลบบัญชี", "en": "Account Deletion Steps"},
    "active_status": {"th": "สถานะใช้งาน", "en": "Active Status"},
    "add_all": {"th": "เพิ่มทั้งหมด", "en": "Add All"},
    "add_all_products": {"th": "เพิ่มสินค้าทั้งหมด", "en": "Add All Products"},
    "add_attachment": {"th": "เพิ่มไฟล์แนบ", "en": "Add Attachment"},
    "add_line_oa_friend": {"th": "เพิ่มเพื่อน LINE OA (ถ้ายังไม่ได้เพิ่ม)", "en": "Add LINE OA Friend (if not added)"},
    "add_permission_success": {"th": "เพิ่มสิทธิ์สำเร็จ", "en": "Permission added successfully"},
    "add_points_failed": {"th": "เพิ่มแต้มไม่สำเร็จ", "en": "Failed to add points"},
    "add_success": {"th": "เพิ่มสำเร็จ", "en": "Added successfully"},
    "additional_items": {"th": "รายการเพิ่มเติม", "en": "Additional Items"},
    "advance_payment_amount": {"th": "ยอดเงินล่วงหน้า:", "en": "Advance Payment Amount:"},
    "advance_payment_deduction": {"th": "ยอดตัดเงินล่วงหน้า", "en": "Advance Payment Deduction"},
    "ai_thinking": {"th": "AI กำลังคิด...", "en": "AI is thinking..."},
    "all_permissions": {"th": "ทุกสิทธิ์", "en": "All Permissions"},
    "amount_range": {"th": "ช่วงจำนวนเงิน", "en": "Amount Range"},
    "analysis_date_range": {"th": "ช่วงวันที่วิเคราะห์", "en": "Analysis Date Range"},
    "analysis_dimension": {"th": "มิติการวิเคราะห์", "en": "Analysis Dimension"},
    "analysis_result_here": {"th": "ผลการวิเคราะห์จะแสดงที่นี่", "en": "Analysis results will display here"},
    "analyze_product": {"th": "วิเคราะห์สินค้านี้:", "en": "Analyze this product:"},
    "approved_auto": {"th": "อนุมัติ(อัตโนมัติ)", "en": "Approved (Auto)"},
    "area": {"th": "พื้นที่", "en": "Area"},
    "audit_check_cost_table": {"th": "ตรวจสอบตารางต้นทุนสินค้า", "en": "Check Product Cost Table"},
    "audit_match": {"th": "ตรงกัน", "en": "Match"},
    "audit_not_match": {"th": "ไม่ตรงกัน", "en": "Not Match"},
    "baht_per_unit": {"th": "บาท/", "en": "Baht/"},
    "barcode_label": {"th": "บาร์โค้ด:", "en": "Barcode:"},
    "branch_config_changed": {"th": "การตั้งค่าสาขาเปลี่ยนแปลง", "en": "Branch Config Changed"},
    "by_user": {"th": "โดย:", "en": "By:"},
    "cancel_reason": {"th": "เหตุผลการยกเลิก", "en": "Cancel Reason"},
    "cancel_status": {"th": "สถานะยกเลิก", "en": "Cancel Status"},
    "cannot_create_code": {"th": "ไม่สามารถสร้างรหัสได้", "en": "Cannot create code"},
    "cannot_get_current_location": {"th": "ไม่สามารถหาตำแหน่งปัจจุบันได้", "en": "Cannot get current location"},
    "cannot_load_attachments": {"th": "ไม่สามารถโหลดรายการไฟล์แนบได้", "en": "Cannot load attachments"},
    "cannot_load_bill_detail": {"th": "ไม่สามารถโหลดรายละเอียดบิลได้", "en": "Cannot load bill details"},
    "cannot_open_file": {"th": "ไม่สามารถเปิดไฟล์ได้", "en": "Cannot open file"},
    "cannot_open_print_page": {"th": "ไม่สามารถเปิดหน้าพิมพ์ได้", "en": "Cannot open print page"},
    "cannot_process": {"th": "ไม่สามารถดำเนินการได้", "en": "Cannot process"},
    "chatbot_all_providers_failed": {"th": "AI Provider ที่มี API Key ลองแล้วใช้ไม่ได้ทุกตัว", "en": "All AI Providers with API Keys failed"},
    "chatbot_api_key_not_set": {"th": "ยังไม่ได้ตั้งค่า API Key", "en": "API Key not configured"},
    "chatbot_auto_retry": {"th": "กำลังลองใหม่อัตโนมัติ", "en": "Auto retrying"},
    "chatbot_fetching_data": {"th": "กำลังดึงข้อมูลจากระบบ อาจใช้เวลาสักครู่", "en": "Fetching data from system, please wait"},
    "chatbot_no_ai_provider": {"th": "ไม่มี AI Provider ที่พร้อมใช้งาน", "en": "No AI Provider available"},
    "chatbot_quota_exceeded": {"th": "AI API โควต้าหมด", "en": "AI API quota exceeded"},
    "chatbot_rate_limit": {"th": "เรียก AI บ่อยเกินไป — กรุณารอสักครู่แล้วลองใหม่", "en": "AI rate limit — please wait and try again"},
    "chatbot_retry_exhausted": {"th": "ลองใหม่ครบจำนวนครั้งแล้ว กรุณารอสักครู่", "en": "Retry attempts exhausted, please wait"},
    "chatbot_retry_in_seconds": {"th": "ลองใหม่อีกครั้ง", "en": "Retrying"},
    "chatbot_suggestion_business_health": {"th": "สุขภาพธุรกิจเป็นอย่างไร", "en": "How is business health?"},
    "chatbot_suggestion_compare_sales": {"th": "เปรียบเทียบยอดขายเดือนนี้กับเดือนที่แล้ว", "en": "Compare this month sales with last month"},
    "chatbot_suggestion_daily_sales": {"th": "ยอดขายวันนี้เท่าไหร่", "en": "What are today sales?"},
    "chatbot_suggestion_low_stock": {"th": "สินค้าไหนใกล้หมดสต็อก", "en": "Which products are low on stock?"},
    "chatbot_suggestion_monthly_profit": {"th": "กำไรเดือนนี้เท่าไหร่", "en": "What is this month profit?"},
    "chatbot_suggestion_top_customers": {"th": "ลูกค้ารายใหญ่ 5 อันดับแรก", "en": "Top 5 customers"},
    "chatbot_suggestion_top_selling": {"th": "สินค้าขายดี 10 อันดับเดือนนี้", "en": "Top 10 selling products this month"},
    "chatbot_tools_used": {"th": "AI ใช้ข้อมูลจาก:", "en": "AI used data from:"},
    "check_permission": {"th": "ตรวจสอบสิทธิ์", "en": "Check Permission"},
    "click_to_select_date": {"th": "กดที่นี่เพื่อเลือกวันที่", "en": "Click to select date"},
    "close_document_success": {"th": "ปิดเอกสารเรียบร้อย", "en": "Document closed successfully"},
    "code_expired": {"th": "รหัสหมดอายุ", "en": "Code expired"},
    "code_expires_in_30_min": {"th": "รหัสหมดอายุใน 30 นาที", "en": "Code expires in 30 minutes"},
    "code_label": {"th": "รหัส:", "en": "Code:"},
    "color_red": {"th": "สีแดง", "en": "Red"},
    "config_reloaded": {"th": "โหลดการตั้งค่าใหม่", "en": "Config Reloaded"},
    "confirm_count": {"th": "ยืนยัน", "en": "Confirm"},
    "confirm_delete_file": {"th": "ต้องการลบไฟล์หรือไม่?", "en": "Delete this file?"},
    "confirm_delete_permission": {"th": "ต้องการลบสิทธิ์หรือไม่?", "en": "Delete this permission?"},
    "confirm_delete_type": {"th": "ต้องการลบประเภทหรือไม่?", "en": "Delete this type?"},
    "confirm_delete_type_with_rules": {"th": "ต้องการลบประเภทหรือไม่? การลบจะลบกฎการอนุมัติที่เกี่ยวข้องด้วย", "en": "Delete this type? Related approval rules will also be deleted"},
    "confirm_delete_user": {"th": "ต้องการลบผู้ใช้หรือไม่?", "en": "Delete this user?"},
    "confirm_link": {"th": "กดยืนยันการเชื่อมต่อ", "en": "Confirm connection"},
    "confirm_remove_from_lineoa": {"th": "ต้องการลบออกจาก LINE OA หรือไม่?", "en": "Remove from LINE OA?"},
    "confirm_withdraw_approval": {"th": "ต้องการถอนการส่งอนุมัติเอกสารนี้หรือไม่?", "en": "Withdraw approval for this document?"},
    "copied": {"th": "คัดลอกแล้ว", "en": "Copied"},
    "copy_permission": {"th": "คัดลอกสิทธิ์", "en": "Copy Permission"},
    "copy_permission_from": {"th": "คัดลอกสิทธิ์จาก", "en": "Copy Permission From"},
    "copy_permission_success": {"th": "คัดลอกสิทธิ์สำเร็จ", "en": "Permission copied successfully"},
    "cost_calculation_test_result": {"th": "ผลการทดสอบคำนวณต้นทุน", "en": "Cost Calculation Test Result"},
    "create_connect_link": {"th": "สร้างลิงก์เชื่อมต่อ", "en": "Create Connect Link"},
    "creating_code": {"th": "กำลังสร้างรหัส...", "en": "Creating code..."},
    "creating_sub_shop": {"th": "กำลังสร้างร้านย่อย...", "en": "Creating sub shop..."},
    "creditor_not_found": {"th": "ไม่พบเจ้าหนี้", "en": "Creditor not found"},
    "currency_code_length_error": {"th": "รหัสสกุลเงินต้องมีความยาว 2-5 ตัวอักษร", "en": "Currency code must be 2-5 characters"},
    "current_shop_id": {"th": "Shop ID ปัจจุบัน:", "en": "Current Shop ID:"},
    "custom_form": {"th": "ฟอร์มที่กำหนดเอง", "en": "Custom Form"},
    "customer_debtor": {"th": "ลูกค้า/ลูกหนี้", "en": "Customer/Debtor"},
    "date_out_of_range": {"th": "วันที่ต้องอยู่ในช่วง", "en": "Date must be in range"},
    "debtor_customer_name": {"th": "ชื่อลูกหนี้/ลูกค้า", "en": "Debtor/Customer Name"},
    "debtor_not_found": {"th": "ไม่พบลูกหนี้", "en": "Debtor not found"},
    "debtor_points": {"th": "แต้มลูกหนี้", "en": "Debtor Points"},
    "decimal_places_cost": {"th": "จุดทศนิยม (ต้นทุน)", "en": "Decimal Places (Cost)"},
    "decimal_places_quantity": {"th": "จุดทศนิยม (จำนวน)", "en": "Decimal Places (Quantity)"},
    "decimal_places_value": {"th": "จุดทศนิยม (มูลค่า)", "en": "Decimal Places (Value)"},
    "delete_file": {"th": "ลบไฟล์", "en": "Delete File"},
    "delete_file_success": {"th": "ลบไฟล์สำเร็จ", "en": "File deleted successfully"},
    "delete_permission_success": {"th": "ลบสิทธิ์สำเร็จ", "en": "Permission deleted successfully"},
    "delete_point_transaction_success": {"th": "ลบรายการเพิ่มแต้มสำเร็จ", "en": "Point transaction deleted successfully"},
    "delete_this_product": {"th": "ลบสินค้านี้", "en": "Delete This Product"},
    "description_required": {"th": "คำอธิบาย", "en": "Description"},
    "deselect_category": {"th": "ยกเลิกหมวด", "en": "Deselect Category"},
    "disabled": {"th": "ปิดใช้งาน", "en": "Disabled"},
    "doc_already_exists": {"th": "เลขที่เอกสารมีอยู่ในระบบแล้ว", "en": "Document number already exists"},
    "doc_cancelled": {"th": "เอกสารนี้ถูกยกเลิกแล้ว", "en": "Document has been cancelled"},
    "doc_closed": {"th": "เอกสารนี้รับครบแล้ว", "en": "Document is fully received"},
    "doc_closed_manual": {"th": "เอกสารถูกปิดด้วยมือ", "en": "Document manually closed"},
    "doc_deleted": {"th": "เอกสารนี้ถูกลบแล้ว", "en": "Document has been deleted"},
    "doc_no_label": {"th": "เลขที่:", "en": "Doc No:"},
    "doc_referenced": {"th": "เอกสารนี้ถูกอ้างอิงแล้ว", "en": "Document has been referenced"},
    "document_already_added": {"th": "เอกสารถูกเพิ่มแล้ว", "en": "Document already added"},
    "document_already_used": {"th": "เอกสารถูกใช้แล้วในรายการอื่น", "en": "Document already used in another entry"},
    "document_attachments": {"th": "ไฟล์แนบเอกสาร", "en": "Document Attachments"},
    "document_audit_info": {"th": "ข้อมูลผู้สร้าง/ผู้แก้ไข", "en": "Creator/Editor Info"},
    "download_template_failed": {"th": "ดาวน์โหลดไฟล์ไม่สำเร็จ", "en": "Download failed"},
    "download_template_success": {"th": "ดาวน์โหลดไฟล์ template สำเร็จ", "en": "Template downloaded successfully"},
    "download_url_not_found": {"th": "ไม่พบ URL สำหรับดาวน์โหลดไฟล์", "en": "Download URL not found"},
    "dual_currency": {"th": "2 สกุลเงิน", "en": "Dual Currency"},
    "edit_all": {"th": "แก้ไขทั้งหมด", "en": "Edit All"},
    "edit_permission_success": {"th": "แก้ไขสิทธิ์สำเร็จ", "en": "Permission edited successfully"},
    "edit_purchase_type": {"th": "แก้ไขประเภทการจัดซื้อ", "en": "Edit Purchase Type"},
    "edit_quotation_type": {"th": "แก้ไขประเภทใบเสนอราคา", "en": "Edit Quotation Type"},
    "edit_sale_order_type": {"th": "แก้ไขประเภทใบสั่งขาย", "en": "Edit Sale Order Type"},
    "edit_type_info": {"th": "แก้ไขข้อมูลประเภท:", "en": "Edit Type Info:"},
    "enable_location_service": {"th": "กรุณาเปิด Location Service ในการตั้งค่าเครื่อง", "en": "Please enable Location Service in device settings"},
    "error_loading": {"th": "เกิดข้อผิดพลาดในการโหลดข้อมูล", "en": "Error loading data"},
    "fetching_data": {"th": "กำลังดึงข้อมูล", "en": "Fetching data"},
    "file_description": {"th": "คำอธิบายไฟล์", "en": "File Description"},
    "file_too_large": {"th": "ไฟล์ใหญ่เกิน", "en": "File too large"},
    "font_preview_text": {"th": "สวัสดีครับ Hello World", "en": "Hello World"},
    "form_booking_desc": {"th": "แบบฟอร์มใบรับจองสินค้า/บริการ", "en": "Booking Form"},
    "form_purchase_order_desc": {"th": "แบบฟอร์มใบสั่งซื้อสินค้า", "en": "Purchase Order Form"},
    "form_quotation_desc": {"th": "แบบฟอร์มใบเสนอราคาสินค้า/บริการ", "en": "Quotation Form"},
    "found_n_records": {"th": "พบ", "en": "Found"},
    "fulltext_search": {"th": "ค้นหาทั่วไป (Full-text)", "en": "Full-text Search"},
    "general_settings": {"th": "การตั้งค่าทั่วไป", "en": "General Settings"},
    "generating": {"th": "กำลังสร้าง...", "en": "Generating..."},
    "gl_creditor_name": {"th": "ชื่อเจ้าหนี้ :", "en": "Creditor Name:"},
    "gl_customer_name": {"th": "ชื่อลูกค้า :", "en": "Customer Name:"},
    "gl_employee_name": {"th": "ชื่อพนักงาน :", "en": "Employee Name:"},
    "gl_inquiry_type": {"th": "ประเภทรายการ :", "en": "Transaction Type:"},
    "gl_make_payment": {"th": "จ่ายชำระ", "en": "Make Payment"},
    "gl_purchase": {"th": "ซื้อสินค้า", "en": "Purchase"},
    "gl_receive_from_requisition": {"th": "รับคืนจากการเบิก", "en": "Receive from Requisition"},
    "gl_receive_payment": {"th": "รับชำระ", "en": "Receive Payment"},
    "gl_receive_product": {"th": "รับสินค้า", "en": "Receive Product"},
    "gl_receive_return": {"th": "รับคืนสินค้า", "en": "Receive Return"},
    "gl_remark": {"th": "หมายเหตุ :", "en": "Remark:"},
    "gl_requisition": {"th": "เบิกสินค้า", "en": "Requisition"},
    "gl_return_product": {"th": "ส่งคืนสินค้า", "en": "Return Product"},
    "gl_sale": {"th": "ขายสินค้า", "en": "Sale"},
    "gl_stock_adjustment": {"th": "ปรับปรุงสต็อก", "en": "Stock Adjustment"},
    "gl_vat_type": {"th": "ประเภทภาษี :", "en": "VAT Type:"},
    "go_add_purchase_type": {"th": "ไปเพิ่มประเภทการจัดซื้อ", "en": "Go Add Purchase Type"},
    "go_add_quotation_type": {"th": "ไปเพิ่มประเภทใบเสนอราคา", "en": "Go Add Quotation Type"},
    "go_add_sale_order_type": {"th": "ไปเพิ่มประเภทใบสั่งขาย", "en": "Go Add Sale Order Type"},
    "grand_total": {"th": "ยอดรวมทั้งสิ้น:", "en": "Grand Total:"},
    "hide_border": {"th": "ไม่แสดงกรอบ", "en": "Hide Border"},
    "how_it_works": {"th": "วิธีทำงาน", "en": "How It Works"},
    "import_debtor_data": {"th": "นำเข้าข้อมูลลูกหนี้", "en": "Import Debtor Data"},
    "import_debtor_points": {"th": "นำเข้าแต้มลูกหนี้", "en": "Import Debtor Points"},
    "import_error": {"th": "เกิดข้อผิดพลาดในการ Import", "en": "Import Error"},
    "import_points_failed": {"th": "นำเข้าแต้มไม่สำเร็จ", "en": "Import points failed"},
    "import_points_success": {"th": "นำเข้าแต้มสำเร็จ", "en": "Import points success"},
    "import_select_template": {"th": "เลือก Template ที่ต้องการดาวน์โหลด", "en": "Select Template to Download"},
    "import_select_type": {"th": "เลือกประเภทข้อมูลที่ต้องการนำเข้า", "en": "Select Data Type to Import"},
    "importing_data": {"th": "กำลังนำเข้า", "en": "Importing"},
    "job_position": {"th": "ตำแหน่งงาน", "en": "Job Position"},
    "label_general_description": {"th": "เหมาะสำหรับการพิมพ์ทั่วไป", "en": "Suitable for general printing"},
    "label_special_price_description": {"th": "เหมาะสำหรับการเน้นราคาพิเศษ", "en": "Suitable for highlighting special prices"},
    "landscape": {"th": "แนวนอน (Landscape)", "en": "Landscape"},
    "last_modifier": {"th": "ผู้แก้ไขล่าสุด", "en": "Last Modified By"},
    "line_connect_success": {"th": "เชื่อมต่อ LINE สำเร็จ", "en": "LINE connected successfully"},
    "line_disconnected": {"th": "ยกเลิกการเชื่อมต่อ LINE แล้ว", "en": "LINE disconnected"},
    "lineoa_config_title": {"th": "ตั้งค่า LINE OA", "en": "LINE OA Settings"},
    "link_success": {"th": "เชื่อมต่อสำเร็จ!", "en": "Connected successfully!"},
    "linked_permissions": {"th": "สิทธิ์ที่เชื่อม:", "en": "Linked Permissions:"},
    "loading_approval_status": {"th": "กำลังโหลดสถานะอนุมัติ...", "en": "Loading approval status..."},
    "loading_locations": {"th": "กำลังโหลดตำแหน่งที่เก็บ...", "en": "Loading locations..."},
    "loading_more_data": {"th": "กำลังโหลดข้อมูลเพิ่ม...", "en": "Loading more data..."},
    "loading_products": {"th": "กำลังโหลดรายการสินค้า...", "en": "Loading products..."},
    "loading_warehouse": {"th": "กำลังโหลดคลังสินค้า...", "en": "Loading warehouses..."},
    "location_permission_denied": {"th": "สิทธิ์การเข้าถึงตำแหน่งถูกปฏิเสธ", "en": "Location permission denied"},
    "manual_close_document": {"th": "ปิดเอกสารด้วยมือ", "en": "Manual Close Document"},
    "max_amount": {"th": "จำนวนเงินสูงสุด", "en": "Max Amount"},
    "max_approval_amount": {"th": "วงเงินอนุมัติสูงสุด (บาท)", "en": "Max Approval Amount (Baht)"},
    "mcp_custom_description": {"th": "เลือก tools เองทีละตัว", "en": "Select tools individually"},
    "mcp_readonly_description": {"th": "ดูข้อมูลอย่างเดียว — เหมาะกับ Claude Desktop", "en": "Read only — suitable for Claude Desktop"},
    "mcp_readwrite_description": {"th": "อ่าน+เขียน ทุก tool — เหมาะกับ backend dev", "en": "Read+Write all tools — suitable for backend dev"},
    "min_amount": {"th": "จำนวนเงินต่ำสุด", "en": "Min Amount"},
    "my_form": {"th": "ฟอร์มของฉัน", "en": "My Form"},
    "net_sales_value": {"th": "มูลค่าขายสุทธิ", "en": "Net Sales Value"},
    "new_permission_code": {"th": "รหัสสิทธิ์ใหม่", "en": "New Permission Code"},
    "new_permission_name": {"th": "ชื่อสิทธิ์ใหม่", "en": "New Permission Name"},
    "no_attachments": {"th": "ไม่มีไฟล์แนบ", "en": "No Attachments"},
    "no_audit_info": {"th": "ยังไม่มีข้อมูลประวัติการแก้ไข", "en": "No edit history available"},
    "no_available_permissions": {"th": "ไม่มีสิทธิ์ที่ใช้งานได้", "en": "No available permissions"},
    "no_condition_show_all": {"th": "ไม่มีเงื่อนไข - แสดงทั้งหมด", "en": "No condition - show all"},
    "no_purchase_type_data": {"th": "ไม่พบข้อมูลประเภทการจัดซื้อ", "en": "No purchase type data found"},
    "no_purchase_types": {"th": "ยังไม่มีประเภทการจัดซื้อ", "en": "No purchase types"},
    "no_quotation_types": {"th": "ยังไม่มีประเภทใบเสนอราคา", "en": "No quotation types"},
    "no_sale_order_types": {"th": "ยังไม่มีประเภทใบสั่งขาย", "en": "No sale order types"},
    "not_activated": {"th": "ยังไม่เปิดใช้งาน", "en": "Not Activated"},
    "not_display": {"th": "ไม่แสดง", "en": "Not Display"},
    "not_selected": {"th": "ไม่ได้เลือก", "en": "Not Selected"},
    "open_document_success": {"th": "เปิดเอกสารเรียบร้อย", "en": "Document opened successfully"},
    "page_number": {"th": "หน้า", "en": "Page"},
    "payment_info": {"th": "ข้อมูลยอดเงิน", "en": "Payment Info"},
    "pdf_approver": {"th": "ผู้อนุมัติ", "en": "Approver"},
    "pdf_credit_note_tax_invoice": {"th": "ใบลดหนี้/ใบกำกับภาษี", "en": "Credit Note/Tax Invoice"},
    "pdf_deliverer": {"th": "ผู้นำส่ง", "en": "Deliverer"},
    "pdf_exchange_rate_label": {"th": "อัตราแลกเปลี่ยน:", "en": "Exchange Rate:"},
    "pdf_font_setting": {"th": "Font สำหรับ PDF", "en": "PDF Font Setting"},
    "pdf_goods_receiver": {"th": "ผู้รับสินค้า", "en": "Goods Receiver"},
    "pdf_goods_sender": {"th": "ผู้ส่งสินค้า", "en": "Goods Sender"},
    "pdf_location_in": {"th": "ที่เก็บ/เข้า", "en": "Location/In"},
    "pdf_location_out": {"th": "ที่เก็บ/ออก", "en": "Location/Out"},
    "pdf_money_receiver": {"th": "ผู้รับเงิน", "en": "Money Receiver"},
    "pdf_on_behalf_of": {"th": "ในนาม", "en": "On Behalf Of"},
    "pdf_orderer": {"th": "ผู้สั่งซื้อ", "en": "Orderer"},
    "pdf_partial_receive": {"th": "รับสินค้าแบบบางส่วน", "en": "Partial Receive"},
    "pdf_payer": {"th": "ผู้จ่ายเงิน", "en": "Payer"},
    "pdf_preview": {"th": "ตัวอย่าง PDF", "en": "PDF Preview"},
    "pdf_purchaser": {"th": "ผู้สั่งซื้อ", "en": "Purchaser"},
    "pdf_purchase_return_doc": {"th": "ใบส่งคืนสินค้า", "en": "Purchase Return"},
    "pdf_receiver": {"th": "ผู้รับของ", "en": "Receiver"},
    "pdf_recorder": {"th": "ผู้บันทึก", "en": "Recorder"},
    "pdf_requester": {"th": "ผู้เบิก", "en": "Requester"},
    "pdf_return_from_pickup": {"th": "ใบรับคืนจากการเบิก", "en": "Return from Pickup"},
    "pdf_return_receiver": {"th": "ผู้รับคืน", "en": "Return Receiver"},
    "pdf_sale_order_doc": {"th": "ใบสั่งขายสินค้า", "en": "Sale Order"},
    "pdf_seller": {"th": "ผู้ขาย", "en": "Seller"},
    "pdf_stock_adjustment": {"th": "ใบปรับปรุงสต๊อก", "en": "Stock Adjustment"},
    "pdf_stock_transfer": {"th": "ใบโอนสินค้า", "en": "Stock Transfer"},
    "pdf_tax_id": {"th": "เลขประจำตัวผู้เสียภาษีอากร :", "en": "Tax ID:"},
    "pdf_total_cost": {"th": "รวมต้นทุน", "en": "Total Cost"},
    "pdf_warehouse_in": {"th": "คลัง/เข้า", "en": "Warehouse/In"},
    "pdf_warehouse_out": {"th": "คลัง/ออก", "en": "Warehouse/Out"},
    "permission_code_required": {"th": "รหัสสิทธิ์", "en": "Permission Code"},
    "permission_level": {"th": "ระดับสิทธิ์", "en": "Permission Level"},
    "permission_name_label": {"th": "ชื่อสิทธิ์", "en": "Permission Name"},
    "please_create_new_code": {"th": "กรุณาสร้างรหัสใหม่", "en": "Please create new code"},
    "please_enter_point_amount": {"th": "กรุณาระบุจำนวนแต้ม", "en": "Please enter point amount"},
    "please_enter_reason": {"th": "กรุณากรอกเหตุผล", "en": "Please enter reason"},
    "please_fill_all_fields": {"th": "กรุณากรอกข้อมูลให้ครบ", "en": "Please fill all fields"},
    "please_select_date": {"th": "โปรดเลือกวันที่ที่ต้องการ", "en": "Please select a date"},
    "please_select_location": {"th": "โปรดเลือกตำแหน่งที่เก็บก่อน", "en": "Please select a location first"},
    "please_select_point_code": {"th": "กรุณาเลือกรหัสแต้มก่อน", "en": "Please select point code first"},
    "please_select_shelf": {"th": "โปรดเลือกชั้นวางเพื่อดูรายการสินค้า", "en": "Please select a shelf to view products"},
    "please_select_warehouse": {"th": "โปรดเลือกคลังสินค้าก่อน", "en": "Please select a warehouse first"},
    "po_approved_title": {"th": "PO ได้รับการอนุมัติ", "en": "PO Approved"},
    "po_rejected_title": {"th": "PO ถูกปฏิเสธ", "en": "PO Rejected"},
    "point_amount": {"th": "จำนวนแต้ม", "en": "Point Amount"},
    "point_amount_must_be_positive": {"th": "จำนวนแต้มต้องมากกว่า 0", "en": "Point amount must be greater than 0"},
    "point_balance": {"th": "แต้มคงเหลือ", "en": "Point Balance"},
    "point_code_label": {"th": "รหัสแต้ม:", "en": "Point Code:"},
    "portrait": {"th": "แนวตั้ง (Portrait)", "en": "Portrait"},
    "print_all": {"th": "พิมพ์ทั้งหมด", "en": "Print All"},
    "print_date": {"th": "วันที่พิมพ์:", "en": "Print Date:"},
    "print_error": {"th": "เกิดข้อผิดพลาดในการพิมพ์", "en": "Print error"},
    "print_shelf_label_complete": {"th": "พิมพ์ป้ายชั้นวางสินค้าเสร็จสมบูรณ์", "en": "Shelf label printing completed"},
    "processing_duration": {"th": "ระยะเวลาประมวลผล", "en": "Processing Duration"},
    "processing_items": {"th": "กำลังประมวลผล", "en": "Processing"},
    "processing_mode": {"th": "รูปแบบการประมวลผล", "en": "Processing Mode"},
    "product_items_count": {"th": "รายการสินค้า", "en": "Product Items"},
    "properties_label": {"th": "คุณสมบัติ:", "en": "Properties:"},
    "quota_exceeded": {"th": "โควต้าหมด", "en": "Quota Exceeded"},
    "quotation_validity_note": {"th": "ใบเสนอราคานี้มีอายุ 30 วัน", "en": "This quotation is valid for 30 days"},
    "reason_required": {"th": "เหตุผล (จำเป็น)", "en": "Reason (Required)"},
    "reconnect_line": {"th": "เชื่อมต่อ LINE ใหม่", "en": "Reconnect LINE"},
    "related_customer_debtor": {"th": "ลูกค้า/ลูกหนี้ที่เกี่ยวข้อง", "en": "Related Customer/Debtor"},
    "remaining_balance": {"th": "ยอดคงเหลือ:", "en": "Remaining Balance:"},
    "resend_notification": {"th": "แจ้งเตือนซ้ำ", "en": "Resend Notification"},
    "sales_quantity": {"th": "จำนวนขาย", "en": "Sales Quantity"},
    "save_permission_success": {"th": "บันทึกสิทธิ์สำเร็จ", "en": "Permission saved successfully"},
    "scan_qr_with_line": {"th": "Scan QR Code ด้วย LINE", "en": "Scan QR Code with LINE"},
    "search_all_fields": {"th": "คำค้นหา (ค้นหาทุกฟิลด์)", "en": "Search (all fields)"},
    "search_barcode_or_product": {"th": "กรอกบาร์โค้ดหรือชื่อสินค้า", "en": "Enter barcode or product name"},
    "search_debtor_hint": {"th": "พิมพ์ รหัส/ชื่อลูกหนี้ เพื่อค้นหา", "en": "Type code/name to search debtor"},
    "search_document": {"th": "ค้นหาเอกสาร", "en": "Search Document"},
    "search_permission_hint": {"th": "ค้นหารหัสสิทธิ์หรือชื่อสิทธิ์...", "en": "Search permission code or name..."},
    "search_seller_creditor": {"th": "ค้นหาผู้ขาย/เจ้าหนี้", "en": "Search Seller/Creditor"},
    "search_text_in_document": {"th": "ค้นหาข้อความในเอกสาร", "en": "Search text in document"},
    "search_user_hint": {"th": "ค้นหาผู้ใช้งาน...", "en": "Search user..."},
    "select_category": {"th": "เลือกหมวด", "en": "Select Category"},
    "select_label_print_format": {"th": "กรุณาเลือกรูปแบบการพิมพ์ฉลากสินค้า", "en": "Select label print format"},
    "select_location_for_report": {"th": "เลือกที่เก็บสินค้าที่ต้องการรายงาน", "en": "Select location for report"},
    "select_product_barcode": {"th": "เลือกสินค้า/บาร์โค้ด", "en": "Select Product/Barcode"},
    "select_product_from_shelf": {"th": "เลือกสินค้าจากชั้นวาง", "en": "Select Product from Shelf"},
    "select_purchase_type": {"th": "เลือกประเภทการจัดซื้อ", "en": "Select Purchase Type"},
    "select_warehouse_for_report": {"th": "เลือกคลังสินค้าที่ต้องการรายงาน", "en": "Select warehouse for report"},
    "selected_values_summary": {"th": "สรุปค่าที่เลือก", "en": "Selected Values Summary"},
    "seller_code": {"th": "รหัสผู้ขาย", "en": "Seller Code"},
    "seller_name": {"th": "ชื่อผู้ขาย", "en": "Seller Name"},
    "send_test_message": {"th": "ส่งข้อความทดสอบ", "en": "Send Test Message"},
    "sending": {"th": "กำลังส่ง...", "en": "Sending..."},
    "sending_test_message": {"th": "กำลังส่งข้อความทดสอบ...", "en": "Sending test message..."},
    "shelf_products_count": {"th": "สินค้าในชั้นวาง", "en": "Shelf Products"},
    "show_as_table": {"th": "แสดงแบบตาราง", "en": "Show as Table"},
    "show_border": {"th": "แสดงกรอบ", "en": "Show Border"},
    "show_hide_tips": {"th": "แสดง/ซ่อนคำแนะนำ", "en": "Show/Hide Tips"},
    "show_items": {"th": "แสดงรายการ", "en": "Show Items"},
    "show_product_sub_items": {"th": "แสดงรายการย่อย (สินค้า)", "en": "Show Sub Items (Products)"},
    "single_currency": {"th": "1 สกุลเงิน", "en": "Single Currency"},
    "sort_ascending": {"th": "น้อยไปหามาก", "en": "Ascending"},
    "sort_by_datetime": {"th": "เรียงลำดับตามวันที่-เวลา", "en": "Sort by Date-Time"},
    "sort_descending": {"th": "มากไปหาน้อย", "en": "Descending"},
    "start_from_date": {"th": "เริ่มจากวันที่", "en": "Start From Date"},
    "sub_shop_name": {"th": "ชื่อร้านย่อย", "en": "Sub Shop Name"},
    "tags": {"th": "แท็ก", "en": "Tags"},
    "tax_id": {"th": "เลขประจำตัวผู้เสียภาษี", "en": "Tax ID"},
    "time_label": {"th": "เวลา:", "en": "Time:"},
    "total_by_date": {"th": "รวมวันที่", "en": "Total by Date"},
    "total_n_records": {"th": "ทั้งหมด", "en": "Total"},
    "type_search_keyword": {"th": "พิมพ์คำที่ต้องการค้นหา", "en": "Type search keyword"},
    "unsupported_type": {"th": "ไม่รองรับประเภทนี้", "en": "Unsupported type"},
    "uploaded_by": {"th": "อัปโหลดโดย:", "en": "Uploaded by:"},
    "user_not_connected_line": {"th": "ผู้ใช้ยังไม่ได้เชื่อมต่อ LINE", "en": "User not connected to LINE"},
    "view_file": {"th": "ดูไฟล์", "en": "View File"},
    "waiting_for_link": {"th": "รอการเชื่อมต่อ...", "en": "Waiting for connection..."},
    "warehouse_and_location": {"th": "คลังสินค้าและตำแหน่ง", "en": "Warehouse and Location"},
    "withdraw_approval": {"th": "ถอนการส่งอนุมัติ", "en": "Withdraw Approval"},
}

def main():
    with open(LANG_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)

    added = 0
    skipped = 0
    for key, translations in NEW_KEYS.items():
        if key in data:
            skipped += 1
            continue
        entry = {
            "th": translations["th"],
            "en": translations["en"],
            "cn": translations["en"],
            "ja": translations["en"],
            "km": translations["en"],
            "ko": translations["en"],
            "lo": translations["en"],
            "my": translations["en"],
            "vi": translations["en"],
        }
        data[key] = entry
        added += 1

    sorted_data = dict(sorted(data.items()))

    with open(LANG_FILE, 'w', encoding='utf-8') as f:
        json.dump(sorted_data, f, ensure_ascii=False, indent=2)

    print(f"Added: {added} keys, Skipped (already exist): {skipped}")
    print(f"Total keys now: {len(sorted_data)}")

if __name__ == "__main__":
    main()
