import type { MenuCategory } from "./menu-data";

export type MenuIconKey =
  | "activity"
  | "archive"
  | "badge"
  | "bank"
  | "barChart"
  | "bot"
  | "boxes"
  | "branch"
  | "briefcase"
  | "building"
  | "calendarCheck"
  | "calculator"
  | "category"
  | "check"
  | "cloudDownload"
  | "cloudSync"
  | "color"
  | "creditCard"
  | "currency"
  | "department"
  | "design"
  | "download"
  | "fileChart"
  | "fileCog"
  | "fileText"
  | "folder"
  | "gift"
  | "globe"
  | "grid"
  | "group"
  | "import"
  | "inbox"
  | "inventory"
  | "key"
  | "kitchen"
  | "link"
  | "list"
  | "location"
  | "map"
  | "media"
  | "money"
  | "network"
  | "notification"
  | "outbox"
  | "package"
  | "payment"
  | "photoAdd"
  | "photoLibrary"
  | "pos"
  | "print"
  | "project"
  | "qr"
  | "receipt"
  | "return"
  | "ruler"
  | "sale"
  | "settings"
  | "shield"
  | "shoppingBasket"
  | "shoppingCart"
  | "store"
  | "table"
  | "tag"
  | "truck"
  | "upload"
  | "user"
  | "userAdd"
  | "users"
  | "warehouse"
  | "work";

const CATEGORY_ICON_KEYS: Record<MenuCategory, MenuIconKey> = {
  approval: "check",
  finance: "payment",
  master: "grid",
  report: "barChart",
  restaurant: "store",
  settings: "settings",
  transaction: "briefcase",
};

export const ROUTE_ICON_KEYS: Record<string, MenuIconKey> = {
  "/procurement/requisition-approval": "check",
  "/procurement/order-cancellation": "return",
  "/procurement/price-comparison": "table",
  "/procurement/generate-orders": "shoppingCart",
  "/transaction/landedcost": "calculator",
  "/transaction/purchasereceiptadjustment": "fileCog",
  "/sales/quotation-approval": "check",
  "/sales/quotation-cancellation": "return",
  "/sales/order-approval": "check",
  "/sales/order-cancellation": "return",
  "/sales/reservations": "network",
  "/sales/order-dates": "calendarCheck",
  "/sales/delivery-dates": "truck",
  "/transaction/apotherdebt": "fileText",
  "/transaction/apbillingreceipt": "receipt",
  "/transaction/apbaddebt": "fileCog",
  "/tools/ap-recalculate": "calculator",
  "/tools/ap-bill-balances": "calculator",
  "/transaction/arotherdebt": "fileText",
  "/transaction/arbaddebt": "fileCog",
  "/transaction/temporaryreceipt": "receipt",
  "/tools/ar-recalculate": "calculator",
  "/tools/ar-bill-balances": "calculator",
  "/banking/cheques/deposit": "bank",
  "/banking/cheques/received-clear": "check",
  "/banking/cheques/received-return": "return",
  "/banking/cheques/redeposit": "bank",
  "/banking/cheques/received-cancel": "return",
  "/banking/cheques/discount": "money",
  "/banking/cheques/issued-clear": "check",
  "/banking/cheques/issued-cancel": "return",
  "/banking/cards/receipts": "creditCard",
  "/banking/cards/settlement": "payment",
  "/banking/cards/cancellation": "return",
  "/banking/cash-deposit": "inbox",
  "/banking/cash-withdrawal": "outbox",
  "/banking/charges": "payment",
  "/banking/income": "money",
  "/banking/contacts": "user",
  "/banking/petty-cash-limit": "money",
  "/tools/cheque-balances": "calculator",
  "/tools/bank-balances": "calculator",
  "/inventory/issue-request": "fileText",
  "/inventory/transfer-request": "truck",
  "/inventory/goods-inspection": "check",
  "/inventory/count-sheet": "list",
  "/inventory/product-sets": "boxes",
  "/inventory/set-assembly": "boxes",
  "/inventory/set-disassembly": "package",
  "/inventory/set-components": "list",
  "/inventory/selling-prices": "tag",
  "/promotionscreen": "gift",
  "/inventory/price-adjustment": "money",
  "/inventory/daily-sequence": "list",
  "/asset/maintenance": "fileCog",
  "/asset/types": "category",
  "/asset/post-gl": "fileText",
  "/transaction/purchasevatadjustment": "calculator",
  "/gl/budget": "calculator",
  "/gl/account-groups": "group",
  "/gl/account-mapping": "link",
  "/gl/allocations": "calculator",
  "/gl/product-account-groups": "package",
  "/gl/annual-balances": "fileChart",
  "/gl/posting": "check",
  "/gl/unposting": "return",
  "/gl/reprocess": "calculator",
  "/gl/recalculate-posted": "calculator",
  "/gl/year-end": "calendarCheck",
  "/gl/statement-designer": "design",
  "/": "grid",
  "/menu": "grid",
  "/transaction/purchaserequisition": "fileText",
  "/transaction/rfq": "fileText",
  "/transaction/purchaseorder": "shoppingCart",
  "/procurement/dashboard": "barChart",
  "/transaction/purchase": "inventory",
  "/transaction/purchasereturn": "return",
  "/transaction/purchasepartial": "shoppingCart",
  "/transaction/accrualreceive": "shoppingCart",
  "/transaction/advancepayment": "payment",
  "/transaction/advancepaymentrefund": "money",
  "/transaction/deposit": "money",
  "/transaction/depositrefund": "money",
  "/transaction/quotation": "receipt",
  "/transaction/saleorder": "shoppingCart",
  "/transaction/paidadvance": "money",
  "/transaction/paidadvancerefund": "money",
  "/transaction/receivedeposit": "money",
  "/transaction/receivedepositrefund": "money",
  "/transaction/sale": "pos",
  "/transaction/salereturn": "return",
  "/transaction/stocktransfer": "truck",
  "/transaction/stockreceiveproduct": "inbox",
  "/transaction/stockpickupproduct": "outbox",
  "/transaction/stockreturnproduct": "return",
  "/transaction/adjust": "calculator",
  "/transaction/stockbalance": "inventory",
  "/transaction/paid": "payment",
  "/transaction/pay": "creditCard",
  "/slipmoneyin": "photoAdd",
  "/slipmoneyout": "photoLibrary",
  "/checkdaily/dailyinfoscreen": "calendarCheck",
  "/cashinginthedrawer": "money",
  "/report/stockbalanceitem": "fileText",
  "/report/stockbalancewarehouse": "fileChart",
  "/report/stockbalancelocation": "barChart",
  "/report/stockmovementcost": "barChart",
  "/report/salesreportbydocument": "barChart",
  "/report/reportdedebisales": "fileChart",
  "/report/reportdedebisalesdaily": "fileChart",
  "/report/reportdedebipaymentdaily": "fileChart",
  "/report/reportdedebisalereturn": "fileChart",
  "/report/reportstockmovement": "fileChart",
  "/report/reportdedebistockbalance": "fileChart",
  "/report/reportdedebipurchasepartial": "fileChart",
  "/report/reportgrossprofitbydocument": "fileChart",
  "/report/reportgrossprofitbyproduct": "fileChart",
  "/report/reportvatsale": "fileChart",
  "/report/reportvatbuy": "fileChart",
  "/rebuildstockscreen": "cloudSync",
  "/auditscreen": "archive",
  "/rebuildproductsscreen": "cloudSync",
  "/rebuildproductbalancescreen": "calculator",
  "/product": "package",
  "/productbarcode": "qr",
  "/productunit": "ruler",
  "/productbarcodeshelf": "print",
  "/productserialregistry": "qr",
  "/pricehistory": "money",
  "/productcategorylist": "list",
  "/productgroup": "group",
  "/productwarehousescreen": "warehouse",
  "/masterbrandscreen": "badge",
  "/addproducttobranchscreen": "building",
  "/addproducttodepartmentscreen": "department",
  "/creditor": "user",
  "/creditorgroup": "users",
  "/debtor": "user",
  "/debtorgroup": "users",
  "/bank": "bank",
  "/bookbankscreen": "bank",
  "/importproduct": "upload",
  "/importproductfromfile": "upload",
  "/knowledgebasescreen": "archive",
  "/alertagentscreen": "notification",
  "/importproductimage": "photoLibrary",
  "/addproducttokitchenscreen": "store",
  "/currency": "currency",
  "/businesstypescreen": "category",
  "/activelanguages": "globe",
  "/company": "building",
  "/branch": "branch",
  "/department": "department",
  "/workdayscreen": "calendarCheck",
  "/holidayscreen": "calendarCheck",
  "/employee": "badge",
  "/user": "userAdd",
  "/line-oa": "link",
  "/formdesign": "fileCog",
  "/linenotify": "notification",
  "/permissiondefinition": "shield",
  "/permissiongroup": "users",
  "/approvalsetting": "payment",
  "/permissionlink": "link",
  "/aiprovider": "bot",
  "/copyuattodev": "cloudDownload",
  "/datamodelgraph": "network",
  "/transaction/purchasedebitnote": "return",
  "/transaction/expense": "receipt",
  "/transaction/withholdingtax": "fileText",
  "/transaction/billingnote": "fileText",
  "/transaction/saleinvoice": "receipt",
  "/transaction/taxinvoice": "receipt",
  "/transaction/creditnote": "return",
  "/transaction/debitnote": "fileText",
  "/transaction/etax": "globe",
  "/transaction/stockcount": "calculator",
  "/inventory/cost-layers": "boxes",
  "/banking/statements": "creditCard",
  "/banking/reconciliation": "check",
  "/gl/journal/uv": "fileText",
  "/gl/journal/sv": "fileText",
  "/gl/journal/rv": "money",
  "/gl/journal/pv": "payment",
  "/gl/journal/jv": "fileChart",
  "/gl/journals": "fileText",
  "/gl/chartofaccounts": "list",
  "/gl/fiscal-years": "calendarCheck",
  "/gl/periodlock": "key",
  "/report/pnl": "barChart",
  "/report/balancesheet": "fileChart",
  "/report/trialbalance": "table",
  "/report/cashflow": "money",
  "/report/project-pnl": "project",
  "/report/dimensionpnl": "department",
  "/report/vatpp30": "fileText",
  "/report/wht-reports": "fileChart",
  "/asset/registry": "building",
  "/asset/depreciation": "calculator",
  "/dimensions/tags": "tag",
  "/transaction/documentvault": "archive",
  "/gl/workingpaper": "table",
  "/report/financialgraphs": "activity",
  "/debtorbeginningbalance": "user",
  "/creditorbeginningbalance": "building",
  "/apidashboard": "network",
  "/pettycashscreen": "money",
  "/transaction/chequereceived": "creditCard",
  "/transaction/chequeissued": "creditCard",
  "/transaction/recurringinvoice": "receipt",
  "/transaction/purchasecreditnote": "fileText",
  "/transaction/recurringexpense": "calendarCheck",
  "/transaction/costadjustment": "calculator",
  "/dimensions/projects": "project",
  "/report/araging": "barChart",
  "/report/apaging": "fileChart",
  "/report/expensesummary": "fileChart",
  "/report/vatpnd2": "fileText",
  "/report/vatpnd3": "fileText",
  "/report/vatpnd53": "fileText",
  "/report/whtcertificate": "badge",
  "/transaction/documentinbox": "inbox",
  "/transaction/paymentvoucher": "receipt",
  "/transaction/accounttransfer": "payment",
  "/gl/financialclose": "check",
  "/report/ledger": "table",
  "/report/cashflowforecast": "activity",
  "/report/projectsummary": "project",
  "/report/unreceivedtaxinvoice": "fileChart",
  "/report/vatpp36": "fileText",
  "/report/whtreceived": "badge",
  "/report/salesbyseller": "user",
  "/report/lowstock": "boxes",
  "/asset/disposal": "archive",
  "/dimensions/boq": "calculator",
  "/transaction/purchasetaxinvoice": "fileText",
  "/transaction/otherincomereceipt": "receipt",
  "/transaction/employeeadvance": "money",
  "/transaction/bankpaymentfile": "bank",
  "/gl/openingbalance": "table",
  "/report/dashboard": "barChart",
  "/report/executivesummary": "activity",
  "/report/xbrl": "download",
  "/report/salesbycustomer": "users",
  "/report/salesbychannel": "store",
  "/report/reportdedebipurchase": "fileChart",
  "/report/purchasebyproduct": "package",
  "/importpartner": "upload",
  "/importdocuments": "upload",
  "/inventory/lotexpiry": "boxes",
  "/report/stocklotmovement": "boxes",
  "/report/expiringstock": "notification",
  "/transaction/combinedpayment": "payment",
  "/transaction/combinedreceipt": "receipt",
  "/transaction/creditcardexpense": "creditCard",
  "/transaction/directoradvance": "money",
  "/asset/purchase": "shoppingCart",
  "/asset/cip": "project",
  "/report/assetschedule": "table",
  "/report/deferredtax": "fileText",
  "/useraccessaudit": "shield",
  "/tools/databackup": "cloudDownload",
  "/tools/scheduledreports": "notification",
};

export function menuIconKeyForRoute(route: string, category: MenuCategory): MenuIconKey {
  return ROUTE_ICON_KEYS[route] ?? CATEGORY_ICON_KEYS[category] ?? "grid";
}

export function hasExplicitMenuIcon(route: string): boolean {
  return Object.prototype.hasOwnProperty.call(ROUTE_ICON_KEYS, route);
}
