import type { MenuCategory } from "./menu-data";

export type MenuIconKey =
  | "activity"
  | "archive"
  | "badge"
  | "bank"
  | "barChart"
  | "bot"
  | "boxes"
  | "branch"
  | "briefcase"
  | "building"
  | "calendarCheck"
  | "calculator"
  | "category"
  | "check"
  | "cloudDownload"
  | "cloudSync"
  | "color"
  | "creditCard"
  | "currency"
  | "department"
  | "design"
  | "download"
  | "fileChart"
  | "fileCog"
  | "fileText"
  | "folder"
  | "gift"
  | "globe"
  | "grid"
  | "group"
  | "import"
  | "inbox"
  | "inventory"
  | "key"
  | "kitchen"
  | "link"
  | "list"
  | "location"
  | "map"
  | "media"
  | "money"
  | "network"
  | "notification"
  | "outbox"
  | "package"
  | "payment"
  | "photoAdd"
  | "photoLibrary"
  | "pos"
  | "print"
  | "project"
  | "qr"
  | "receipt"
  | "return"
  | "ruler"
  | "sale"
  | "settings"
  | "shield"
  | "shoppingBasket"
  | "shoppingCart"
  | "store"
  | "table"
  | "tag"
  | "truck"
  | "upload"
  | "user"
  | "userAdd"
  | "users"
  | "warehouse"
  | "work";

const CATEGORY_ICON_KEYS: Record<MenuCategory, MenuIconKey> = {
  approval: "check",
  finance: "payment",
  master: "grid",
  report: "barChart",
  restaurant: "store",
  settings: "settings",
  transaction: "briefcase",
};

export const ROUTE_ICON_KEYS: Record<string, MenuIconKey> = {
  "/": "grid",
  "/menu": "grid",
  "/transaction/purchaserequisition": "fileText",
  "/transaction/rfq": "fileText",
  "/transaction/purchaseorder": "shoppingCart",
  "/procurement/dashboard": "barChart",
  "/transaction/purchase": "inventory",
  "/transaction/purchasereturn": "return",
  "/transaction/purchasepartial": "shoppingCart",
  "/transaction/accrualreceive": "shoppingCart",
  "/transaction/advancepayment": "payment",
  "/transaction/advancepaymentrefund": "money",
  "/transaction/deposit": "money",
  "/transaction/depositrefund": "money",
  "/transaction/quotation": "receipt",
  "/transaction/saleorder": "shoppingCart",
  "/transaction/paidadvance": "money",
  "/transaction/paidadvancerefund": "money",
  "/transaction/receivedeposit": "money",
  "/transaction/receivedepositrefund": "money",
  "/transaction/sale": "pos",
  "/transaction/salereturn": "return",
  "/transaction/stocktransfer": "truck",
  "/transaction/stockreceiveproduct": "inbox",
  "/transaction/stockpickupproduct": "outbox",
  "/transaction/stockreturnproduct": "return",
  "/transaction/adjust": "calculator",
  "/transaction/stockbalance": "inventory",
  "/transaction/paid": "payment",
  "/transaction/pay": "creditCard",
  "/slipmoneyin": "photoAdd",
  "/slipmoneyout": "photoLibrary",
  "/checkdaily/dailyinfoscreen": "calendarCheck",
  "/cashinginthedrawer": "money",
  "/report/stockbalanceitem": "fileText",
  "/report/stockbalancewarehouse": "fileChart",
  "/report/stockbalancelocation": "barChart",
  "/report/stockmovementcost": "barChart",
  "/report/salesreportbydocument": "barChart",
  "/report/reportdedebisales": "fileChart",
  "/report/reportdedebisalesdaily": "fileChart",
  "/report/reportdedebipaymentdaily": "fileChart",
  "/report/reportdedebisalereturn": "fileChart",
  "/report/reportstockmovement": "fileChart",
  "/report/reportdedebistockbalance": "fileChart",
  "/report/reportdedebipurchasepartial": "fileChart",
  "/report/reportgrossprofitbydocument": "fileChart",
  "/report/reportgrossprofitbyproduct": "fileChart",
  "/report/reportvatsale": "fileChart",
  "/report/reportvatbuy": "fileChart",
  "/rebuildstockscreen": "cloudSync",
  "/auditscreen": "archive",
  "/rebuildproductsscreen": "cloudSync",
  "/rebuildproductbalancescreen": "calculator",
  "/product": "package",
  "/productextension": "tag",
  "/productbarcode": "qr",
  "/productset": "boxes",
  "/productunit": "ruler",
  "/productbarcodeshelf": "print",
  "/promotionscreen": "gift",
  "/productserialregistry": "qr",
  "/channelprice": "money",
  "/pricehistory": "money",
  "/productcategorygroupselectscreen": "folder",
  "/productcategorylist": "list",
  "/productgroup": "group",
  "/productwarehousescreen": "warehouse",
  "/productcolor": "color",
  "/productsize": "ruler",
  "/productvariantmatrix": "grid",
  "/productdimension": "design",
  "/productbom": "fileText",
  "/masterbrandscreen": "badge",
  "/mastercategoryscreen": "category",
  "/masterclassscreen": "category",
  "/masterdesignscreen": "design",
  "/mastergradescreen": "badge",
  "/mastermodelscreen": "design",
  "/masterpatternscreen": "table",
  "/addproducttobranchscreen": "building",
  "/addproducttodepartmentscreen": "department",
  "/creditor": "user",
  "/creditorgroup": "users",
  "/debtor": "user",
  "/debtorgroup": "users",
  "/colorscreen": "color",
  "/qrprovider": "qr",
  "/bank": "bank",
  "/bookbankscreen": "creditCard",
  "/salechannelscreen": "shoppingBasket",
  "/transportchannelscreen": "truck",
  "/possetting": "pos",
  "/exchangerate": "currency",
  "/posmedia": "media",
  "/pointsetting": "badge",
  "/couponsetting": "badge",
  "/docformat": "fileText",
  "/billdesign": "receipt",
  "/purchasetypescreen": "category",
  "/poapprovalsettingscreen": "check",
  "/quotationtypescreen": "receipt",
  "/qtapprovalsettingscreen": "check",
  "/saleordertypescreen": "shoppingCart",
  "/soapprovalsettingscreen": "sale",
  "/importproduct": "upload",
  "/importproductfromfile": "upload",
  "/knowledgebasescreen": "archive",
  "/alertagentscreen": "notification",
  "/importproductimage": "photoLibrary",
  "/zonegroupselectscreen": "map",
  "/tablegroupselectscreen": "table",
  "/tablemapgroupselectscreen": "map",
  "/kitchengroupselectscreen": "kitchen",
  "/addproducttokitchenscreen": "store",
  "/qrcodeordergroupselectscreen": "qr",
  "/ordertemplatsetting": "receipt",
  "/ordersetting": "settings",
  "/currency": "currency",
  "/businesstypescreen": "category",
  "/activelanguages": "globe",
  "/company": "building",
  "/branch": "branch",
  "/department": "department",
  "/workdayscreen": "calendarCheck",
  "/holidayscreen": "calendarCheck",
  "/employee": "badge",
  "/user": "userAdd",
  "/line-oa": "link",
  "/formdesign": "fileCog",
  "/linenotify": "notification",
  "/permissiondefinition": "shield",
  "/permissiongroup": "users",
  "/approvalsetting": "payment",
  "/permissionlink": "link",
  "/marketplace/shopee": "shoppingBasket",
  "/marketplace/lazada": "shoppingBasket",
  "/marketplace/tiktok": "shoppingBasket",
  "/aiprovider": "bot",
  "/copyuattodev": "cloudDownload",
  "/datamodelgraph": "network",
  "/transaction/purchasedebitnote": "return",
  "/transaction/expense": "receipt",
  "/transaction/withholdingtax": "fileText",
  "/transaction/billingnote": "fileText",
  "/transaction/saleinvoice": "receipt",
  "/transaction/taxinvoice": "receipt",
  "/transaction/creditnote": "return",
  "/transaction/debitnote": "fileText",
  "/transaction/etax": "globe",
  "/transaction/stockcount": "calculator",
  "/inventory/cost-layers": "boxes",
  "/banking/statements": "creditCard",
  "/banking/reconciliation": "check",
  "/banking/rules": "settings",
  "/gl/journal/uv": "fileText",
  "/gl/journal/sv": "fileText",
  "/gl/journal/rv": "money",
  "/gl/journal/pv": "payment",
  "/gl/journal/jv": "fileChart",
  "/gl/chartofaccounts": "list",
  "/gl/periodlock": "key",
  "/report/pnl": "barChart",
  "/report/balancesheet": "fileChart",
  "/report/trialbalance": "table",
  "/report/cashflow": "money",
  "/report/project-pnl": "project",
  "/report/vatpp30": "fileText",
  "/report/wht-reports": "fileChart",
  "/asset/registry": "building",
  "/asset/depreciation": "calculator",
  "/dimensions/tags": "tag",
  "/etaxsetting": "settings",
};

export function menuIconKeyForRoute(route: string, category: MenuCategory): MenuIconKey {
  return ROUTE_ICON_KEYS[route] ?? CATEGORY_ICON_KEYS[category] ?? "grid";
}

export function hasExplicitMenuIcon(route: string): boolean {
  return Object.prototype.hasOwnProperty.call(ROUTE_ICON_KEYS, route);
}
